const DB_KEY='sriNidhiStudyHallV1';
const defaultDB={
 settings:{hallName:'Sri Nidhi Study Hall',monthlyFee:1500,adminUser:'admin',adminPass:'1234'},
 students:[
  {id:'SN001',name:'Anusha',gender:'Female',phone:'9876543210',parentPhone:'9123456780',course:'DSC',seat:'G-01',joinDate:'2026-07-01',status:'Active'},
  {id:'SN002',name:'Kavya',gender:'Female',phone:'9876501234',parentPhone:'9012345678',course:'TET',seat:'G-02',joinDate:'2026-07-03',status:'Active'},
  {id:'SN003',name:'Ramesh',gender:'Male',phone:'9866001122',parentPhone:'9000011111',course:'Police',seat:'B-01',joinDate:'2026-07-05',status:'Active'}
 ],
 fees:[
  {id:crypto.randomUUID(),studentId:'SN001',month:'2026-07',amount:1500,paid:1500,date:'2026-07-05',mode:'UPI'},
  {id:crypto.randomUUID(),studentId:'SN002',month:'2026-07',amount:1500,paid:500,date:'2026-07-06',mode:'Cash'}
 ],
 attendance:[], movements:[]
};
let db=loadDB(); let currentPage='dashboard';
function loadDB(){try{return JSON.parse(localStorage.getItem(DB_KEY))||structuredClone(defaultDB)}catch{return structuredClone(defaultDB)}}
function saveDB(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function el(id){return document.getElementById(id)}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
function studentName(id){return db.students.find(s=>s.id===id)?.name||id}
function today(){return new Date().toISOString().slice(0,10)}
function monthNow(){return new Date().toISOString().slice(0,7)}

el('todayText').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
el('loginBtn').onclick=()=>{const u=el('loginUser').value.trim(),p=el('loginPass').value;if(u===db.settings.adminUser&&p===db.settings.adminPass){el('loginView').classList.add('hidden');el('appView').classList.remove('hidden');render('dashboard')}else el('loginError').textContent='Wrong username or password'};
el('logoutBtn').onclick=()=>location.reload(); el('menuBtn').onclick=()=>el('sidebar').classList.toggle('open');
el('navMenu').onclick=e=>{const b=e.target.closest('button[data-page]');if(!b)return;render(b.dataset.page);el('sidebar').classList.remove('open')};
el('modalClose').onclick=closeModal; el('modal').onclick=e=>{if(e.target===el('modal'))closeModal()};
function openModal(html){el('modalBody').innerHTML=html;el('modal').classList.remove('hidden')}
function closeModal(){el('modal').classList.add('hidden');el('modalBody').innerHTML=''}
function render(page){currentPage=page;document.querySelectorAll('#navMenu button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));el('pageTitle').textContent=({dashboard:'Dashboard',students:'Students',admissions:'Admissions',fees:'Fees',pending:'Pending Fees',attendance:'Attendance',movement:'Entry / Exit',reports:'Reports',settings:'Settings'})[page];({dashboard:renderDashboard,students:renderStudents,admissions:renderAdmissions,fees:renderFees,pending:renderPending,attendance:renderAttendance,movement:renderMovement,reports:renderReports,settings:renderSettings})[page]()}
function renderDashboard(){const m=monthNow();const mf=db.fees.filter(f=>f.month===m),collection=mf.reduce((a,f)=>a+Number(f.paid),0);const pending=db.students.reduce((sum,s)=>{const f=mf.find(x=>x.studentId===s.id);return sum+Math.max(0,db.settings.monthlyFee-(f?.paid||0))},0);const outside=db.movements.filter(x=>x.status==='Outside').length;const att=db.attendance.filter(x=>x.date===today()&&x.status==='Present').length;el('pageContent').innerHTML=`<div class="grid stats">
<div class="stat"><div class="label">Total Students</div><div class="value">${db.students.length}</div></div><div class="stat"><div class="label">This Month Collection</div><div class="value">${money(collection)}</div></div><div class="stat"><div class="label">Pending Amount</div><div class="value">${money(pending)}</div></div><div class="stat"><div class="label">Students Outside</div><div class="value">${outside}</div></div></div>
<div class="two-col"><div class="card"><h3>Quick Actions</h3><div class="actions"><button class="primary" onclick="render('admissions')">+ New Admission</button><button class="secondary" onclick="render('fees')">Add Fee</button><button class="secondary" onclick="render('attendance')">Attendance</button><button class="secondary" onclick="render('movement')">Entry / Exit</button></div></div><div class="card"><h3>Today Summary</h3><div class="quick-list"><div class="quick-item"><span>Present</span><b>${att}</b></div><div class="quick-item"><span>Absent / Not Marked</span><b>${Math.max(0,db.students.length-att)}</b></div><div class="quick-item"><span>Girls</span><b>${db.students.filter(s=>s.gender==='Female').length}</b></div></div></div></div>`}
function renderStudents(){el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="studentSearch" placeholder="Search name / phone / ID"><button class="primary" onclick="render('admissions')">+ Add Student</button></div><div id="studentsTable"></div></div>`;el('studentSearch').oninput=drawStudents;drawStudents()}
function drawStudents(){const q=(el('studentSearch')?.value||'').toLowerCase();const list=db.students.filter(s=>Object.values(s).join(' ').toLowerCase().includes(q));el('studentsTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Gender</th><th>Phone</th><th>Course</th><th>Seat</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td>${s.id}</td><td><b>${s.name}</b></td><td>${s.gender}</td><td>${s.phone}</td><td>${s.course||'-'}</td><td>${s.seat||'-'}</td><td><button class="secondary" onclick="editStudent('${s.id}')">Edit</button> <button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students found</div>'}
function renderAdmissions(){el('pageContent').innerHTML=`<div class="card"><h3>New Student Admission</h3>${studentForm()}</div>`;bindStudentForm()}
function studentForm(s={}){return `<form id="studentForm" class="form-grid"><div class="field"><label>Student ID</label><input name="id" value="${s.id||nextStudentId()}" required ${s.id?'readonly':''}></div><div class="field"><label>Student Name</label><input name="name" value="${s.name||''}" required></div><div class="field"><label>Gender</label><select name="gender"><option ${s.gender==='Female'?'selected':''}>Female</option><option ${s.gender==='Male'?'selected':''}>Male</option></select></div><div class="field"><label>Phone</label><input name="phone" value="${s.phone||''}" required></div><div class="field"><label>Parent Phone</label><input name="parentPhone" value="${s.parentPhone||''}"></div><div class="field"><label>Course / Exam</label><input name="course" value="${s.course||''}"></div><div class="field"><label>Seat Number</label><input name="seat" value="${s.seat||''}"></div><div class="field"><label>Joining Date</label><input type="date" name="joinDate" value="${s.joinDate||today()}"></div><div class="field"><label>Status</label><select name="status"><option>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="span-3 actions"><button class="primary" type="submit">Save Student</button></div></form>`}
function bindStudentForm(editId=null){el('studentForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(editId){db.students=db.students.map(s=>s.id===editId?o:s)}else{if(db.students.some(s=>s.id===o.id))return alert('Student ID already exists');db.students.push(o)}saveDB();closeModal();render('students')}}
function nextStudentId(){return 'SN'+String(db.students.length+1).padStart(3,'0')}
window.editStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Edit Student</h3>${studentForm(s)}`);bindStudentForm(id)};window.deleteStudent=id=>{if(confirm('Delete this student?')){db.students=db.students.filter(s=>s.id!==id);saveDB();drawStudents()}}
function studentOptions(){return db.students.map(s=>`<option value="${s.id}">${s.id} - ${s.name}</option>`).join('')}
function renderFees(){el('pageContent').innerHTML=`<div class="card"><h3>Add Fee Payment</h3><form id="feeForm" class="form-grid"><div class="field"><label>Student</label><select name="studentId" required>${studentOptions()}</select></div><div class="field"><label>Month</label><input type="month" name="month" value="${monthNow()}" required></div><div class="field"><label>Monthly Fee</label><input type="number" name="amount" value="${db.settings.monthlyFee}" required></div><div class="field"><label>Paid Amount</label><input type="number" name="paid" required></div><div class="field"><label>Payment Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Payment Mode</label><select name="mode"><option>Cash</option><option>UPI</option><option>Bank</option></select></div><div class="span-3"><button class="primary">Save Payment</button></div></form></div><div class="card"><h3>Payment History</h3><div id="feeTable"></div></div>`;el('feeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=crypto.randomUUID();o.amount=Number(o.amount);o.paid=Number(o.paid);db.fees.push(o);saveDB();renderFees()};drawFees()}
function drawFees(){const list=[...db.fees].reverse();el('feeTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Month</th><th>Fee</th><th>Paid</th><th>Balance</th><th>Date</th><th>Mode</th><th></th></tr></thead><tbody>${list.map(f=>`<tr><td>${studentName(f.studentId)}</td><td>${f.month}</td><td>${money(f.amount)}</td><td>${money(f.paid)}</td><td>${money(f.amount-f.paid)}</td><td>${f.date}</td><td>${f.mode}</td><td><button class="danger" onclick="deleteFee('${f.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No payments</div>'}
window.deleteFee=id=>{if(confirm('Delete payment?')){db.fees=db.fees.filter(f=>f.id!==id);saveDB();renderFees()}}
function getPending(month=monthNow()){return db.students.map(s=>{const fs=db.fees.filter(f=>f.studentId===s.id&&f.month===month);const paid=fs.reduce((a,f)=>a+Number(f.paid),0);return {...s,paid,balance:Math.max(0,db.settings.monthlyFee-paid)}}).filter(x=>x.balance>0)}
function renderPending(){const list=getPending();el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><h3 style="margin-right:auto">Pending Fee List - ${monthNow()}</h3><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Phone</th><th>Monthly Fee</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${list.map(x=>`<tr><td>${x.id}</td><td>${x.name}</td><td>${x.phone}</td><td>${money(db.settings.monthlyFee)}</td><td>${money(x.paid)}</td><td><b>${money(x.balance)}</b></td><td><span class="badge pending">Pending</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No pending fees</div>'}</div>`}
window.downloadPendingPDF=()=>{const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('Sri Nidhi Study Hall - Pending Fee List',14,18);doc.setFontSize(10);let y=30;doc.text('Month: '+monthNow(),14,y);y+=10;getPending().forEach((x,i)=>{doc.text(`${i+1}. ${x.id} - ${x.name} | Phone: ${x.phone} | Balance: Rs.${x.balance}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save(`Pending-Fees-${monthNow()}.pdf`)}
function renderAttendance(){const d=today();el('pageContent').innerHTML=`<div class="card"><h3>Attendance - ${d}</h3><div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.students.map(s=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);return `<tr><td>${s.id}</td><td>${s.name}</td><td><span class="badge ${a?.status==='Present'?'present':'absent'}">${a?.status||'Not Marked'}</span></td><td><button class="success" onclick="markAttendance('${s.id}','Present')">Present</button> <button class="danger" onclick="markAttendance('${s.id}','Absent')">Absent</button></td></tr>`}).join('')}</tbody></table></div></div>`}
window.markAttendance=(studentId,status)=>{db.attendance=db.attendance.filter(x=>!(x.studentId===studentId&&x.date===today()));db.attendance.push({studentId,date:today(),status,time:new Date().toLocaleTimeString()});saveDB();renderAttendance()}
function renderMovement(){const outside=db.movements.filter(x=>x.status==='Outside');el('pageContent').innerHTML=`<div class="card"><h3>Student Going Out</h3><form id="moveForm" class="form-grid"><div class="field"><label>Student</label><select name="studentId">${studentOptions()}</select></div><div class="field"><label>Out Time</label><input type="datetime-local" name="outTime" value="${new Date().toISOString().slice(0,16)}"></div><div class="field"><label>Expected Return</label><input type="datetime-local" name="expectedReturn"></div><div class="field span-2"><label>Reason / Location</label><input name="reason" placeholder="Reason and location"></div><div class="field"><label>Location Link</label><input name="location" placeholder="Google Maps link"></div><div class="span-3"><button class="primary">Submit</button></div></form></div><div class="card"><h3>Currently Outside</h3>${outside.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Out Time</th><th>Expected Return</th><th>Reason / Location</th><th>Status</th><th>Action</th></tr></thead><tbody>${outside.map(x=>`<tr><td>${studentName(x.studentId)}</td><td>${x.outTime}</td><td>${x.expectedReturn||'-'}</td><td>${x.reason||'-'} ${x.location?`<a target="_blank" href="${x.location}">Map</a>`:''}</td><td><span class="badge outside">Outside</span></td><td><button class="success" onclick="markReturned('${x.id}')">Returned</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students outside</div>'}</div>`;el('moveForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=crypto.randomUUID();o.status='Outside';o.returnTime='';db.movements.push(o);saveDB();renderMovement()}}
window.markReturned=id=>{const x=db.movements.find(m=>m.id===id);if(x){x.status='Returned';x.returnTime=new Date().toISOString().slice(0,16);saveDB();renderMovement()}}
function renderReports(){el('pageContent').innerHTML=`<div class="grid stats"><div class="card"><h3>Student List</h3><p class="muted">All active and inactive students.</p><button class="primary" onclick="downloadStudentsPDF()">Download PDF</button></div><div class="card"><h3>Pending Fees</h3><p class="muted">Current month pending fee list.</p><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div class="card"><h3>Backup</h3><p class="muted">Download complete data backup.</p><button class="secondary" onclick="downloadBackup()">Download JSON</button></div><div class="card"><h3>Print Report</h3><p class="muted">Print current page.</p><button class="secondary" onclick="window.print()">Print</button></div></div>`}
window.downloadStudentsPDF=()=>{const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(16);doc.text('Sri Nidhi Study Hall - Student List',14,18);doc.setFontSize(10);let y=30;db.students.forEach((s,i)=>{doc.text(`${i+1}. ${s.id} - ${s.name} | ${s.phone} | Seat: ${s.seat||'-'} | ${s.course||'-'}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save('Sri-Nidhi-Students.pdf')}
window.downloadBackup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='sri-nidhi-backup.json';a.click();URL.revokeObjectURL(a.href)}
function renderSettings(){el('pageContent').innerHTML=`<div class="card"><h3>Settings</h3><form id="settingsForm" class="form-grid"><div class="field"><label>Study Hall Name</label><input name="hallName" value="${db.settings.hallName}"></div><div class="field"><label>Monthly Fee</label><input type="number" name="monthlyFee" value="${db.settings.monthlyFee}"></div><div class="field"><label>Admin Username</label><input name="adminUser" value="${db.settings.adminUser}"></div><div class="field"><label>Admin Password</label><input name="adminPass" value="${db.settings.adminPass}"></div><div class="span-3 actions"><button class="primary">Save Settings</button><button type="button" class="danger" onclick="resetDemo()">Reset Demo Data</button></div></form></div>`;el('settingsForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.monthlyFee=Number(o.monthlyFee);db.settings=o;saveDB();alert('Settings saved')}}
window.resetDemo=()=>{if(confirm('Reset all data?')){db=structuredClone(defaultDB);saveDB();render('dashboard')}}
window.render=render;
