const DB_KEY='sriNidhiStudyHallV12';
const defaultDB={
 meta:{schemaVersion:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
 settings:{hallName:'Sri Nidhi Study Hall',monthlyFee:1500,feeDueDay:10,adminUser:'admin',adminPass:'1234'},
 students:[
  {id:'SN001',name:'Anusha',gender:'Female',dob:'',phone:'9876543210',parentName:'',parentPhone:'9123456780',emergencyPhone:'',address:'',course:'DSC',batch:'Morning',seat:'G-01',joinDate:'2026-07-01',monthlyFee:1500,idProof:'',status:'Active',photo:''},
  {id:'SN002',name:'Kavya',gender:'Female',dob:'',phone:'9876501234',parentName:'',parentPhone:'9012345678',emergencyPhone:'',address:'',course:'TET',batch:'Morning',seat:'G-02',joinDate:'2026-07-03',monthlyFee:1500,idProof:'',status:'Active',photo:''},
  {id:'SN003',name:'Ramesh',gender:'Male',dob:'',phone:'9866001122',parentName:'',parentPhone:'9000011111',emergencyPhone:'',address:'',course:'Police',batch:'Evening',seat:'B-01',joinDate:'2026-07-05',monthlyFee:1500,idProof:'',status:'Active',photo:''}
 ],
 fees:[
  {id:uid(),studentId:'SN001',month:'2026-07',amount:1500,paid:1500,date:'2026-07-05',mode:'UPI',receipt:'RC001'},
  {id:uid(),studentId:'SN002',month:'2026-07',amount:1500,paid:500,date:'2026-07-06',mode:'Cash',receipt:'RC002'}
 ], attendance:[], movements:[], audit:[]
};
let db=loadDB(), currentPage='dashboard';
function uid(){return (crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2))}
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadDB(){
 try{
  const raw=localStorage.getItem(DB_KEY), data=raw?JSON.parse(raw):clone(defaultDB);
  data.meta=data.meta||{schemaVersion:2,createdAt:new Date().toISOString()};
  data.settings={...clone(defaultDB.settings),...(data.settings||{})};
  for(const key of ['students','fees','attendance','movements','audit','notices','diary']) if(!Array.isArray(data[key])) data[key]=[];
  return data;
 }catch{return clone(defaultDB)}
}
function saveDB(){
 try{db.meta=db.meta||{};db.meta.schemaVersion=2;db.meta.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(db));return true}
 catch(e){alert('Data save కాలేదు. Photo size తగ్గించి మళ్లీ ప్రయత్నించండి.');return false}
}
function logAction(type,details){db.audit=db.audit||[];db.audit.unshift({id:uid(),type,details,time:new Date().toISOString()});db.audit=db.audit.slice(0,250)}
function el(id){return document.getElementById(id)}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
function today(){return new Date().toISOString().slice(0,10)}
function monthNow(){return new Date().toISOString().slice(0,7)}
function studentName(id){return db.students.find(s=>s.id===id)?.name||id}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function hallFee(s){return Number(s?.monthlyFee||db.settings.monthlyFee||0)}
function validPhone(v){return !v||/^[6-9]\d{9}$/.test(String(v).trim())}
function isLateMovement(m){return m.status==='Outside'&&m.expectedReturn&&new Date(m.expectedReturn).getTime()<Date.now()}
function closeMenu(){el('sidebar').classList.remove('open');el('overlay').classList.add('hidden')}
function openMenu(){el('sidebar').classList.add('open');el('overlay').classList.remove('hidden')}

el('todayText').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
el('loginBtn').onclick=()=>{const u=el('loginUser').value.trim(),p=el('loginPass').value;if(u===db.settings.adminUser&&p===db.settings.adminPass){el('loginView').classList.add('hidden');el('appView').classList.remove('hidden');render('dashboard')}else el('loginError').textContent='Wrong username or password'};
el('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')el('loginBtn').click()});
el('logoutBtn').onclick=()=>location.reload();
el('menuBtn').onclick=()=>el('sidebar').classList.contains('open')?closeMenu():openMenu();
el('overlay').onclick=closeMenu;
el('navMenu').onclick=e=>{const b=e.target.closest('button[data-page]');if(!b)return;render(b.dataset.page);closeMenu()};
el('modalClose').onclick=closeModal;el('modal').onclick=e=>{if(e.target===el('modal'))closeModal()};
function openModal(html){el('modalBody').innerHTML=html;el('modal').classList.remove('hidden')}
function closeModal(){el('modal').classList.add('hidden');el('modalBody').innerHTML=''}

function render(page){currentPage=page;document.querySelectorAll('#navMenu button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={dashboard:'Dashboard',students:'Students',admissions:'Admissions',fees:'Fees',pending:'Pending Fees',attendance:'Attendance',movement:'Entry / Exit',notices:'Notices',diary:'Daily Diary',reports:'Reports',settings:'Settings'};el('pageTitle').textContent=titles[page]||page;el('sideHallName').textContent=db.settings.hallName.replace(/Study Hall/i,'').trim()||'Sri Nidhi';({dashboard:renderDashboard,students:renderStudents,admissions:renderAdmissions,fees:renderFees,pending:renderPending,attendance:renderAttendance,movement:renderMovement,notices:renderNotices,diary:renderDiary,reports:renderReports,settings:renderSettings}[page]||renderDashboard)()}

function updateLiveClock(){const clock=el('liveClock');if(clock)clock.textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function renderDashboard(){
 const active=db.students.filter(s=>s.status!=='Inactive');
 const females=active.filter(s=>s.gender==='Female').length;
 const males=active.filter(s=>s.gender==='Male').length;
 const present=db.attendance.filter(a=>a.date===today()&&a.status==='Present').length;
 const absent=db.attendance.filter(a=>a.date===today()&&a.status==='Absent').length;
 const outsideList=db.movements.filter(m=>m.status==='Outside');
 const late=outsideList.filter(isLateMovement).length;
 const month=monthNow();
 const collection=db.fees.filter(f=>f.month===month).reduce((a,f)=>a+Number(f.paid||0),0);
 const pendingList=getPending(month);
 const pending=pendingList.reduce((a,x)=>a+x.balance,0);
 const newAdmissions=active.filter(s=>String(s.joinDate||'').startsWith(month)).length;
 const todayMovements=db.movements.filter(m=>String(m.outTime||'').startsWith(today())).length;
 const notices=(db.notices||[]).filter(n=>n.priority==='Urgent').length;
 const activities=(db.audit||[]).slice(0,6);
 el('pageContent').innerHTML=`
 <div class="dashboard-head">
   <div class="hero"><div><span class="eyebrow">WELCOME BACK</span><h1>${esc(db.settings.hallName)}</h1><p>Student Management, Fees & Security Dashboard</p></div><div class="hero-clock"><span>Live Time</span><b id="liveClock"></b></div></div>
   <button class="notification-btn" onclick="render('notices')" aria-label="Notifications">🔔${notices?`<span>${notices}</span>`:''}</button>
 </div>
 ${late?`<div class="alert-danger"><b>⚠️ Late Return Alert:</b> ${late} student(s) expected return time దాటింది. <button onclick="render('movement')">View</button></div>`:''}
 <div class="dashboard-search"><span>🔎</span><input id="dashboardSearch" placeholder="Search student by name, ID, phone or seat"><button onclick="dashboardStudentSearch()">Search</button></div>
 <div class="grid stats premium-stats">
   ${statCard('👨‍🎓','Total Students',active.length,'All active students','blue')}
   ${statCard('👩','Girls',females,'Female students','pink')}
   ${statCard('👨','Boys',males,'Male students','indigo')}
   ${statCard('✅','Present Today',present,absent?`${absent} absent today`:'Attendance status','green')}
   ${statCard('🚶','Currently Outside',outsideList.length,late?`${late} late return`:'Movement status','orange')}
   ${statCard('💰','This Month Collection',money(collection),'Fee received','teal')}
   ${statCard('⏳','Pending Amount',money(pending),`${pendingList.length} students pending`,'red')}
   ${statCard('📝','New Admissions',newAdmissions,'This month','purple')}
   ${statCard('↔️','Today Entries / Exits',todayMovements,'Movement records','slate')}
 </div>
 <div class="two-col dashboard-panels">
   <div class="card"><div class="card-title-row"><h3>Quick Actions</h3><span>Daily work</span></div><div class="quick-action-grid"><button class="quick-action primary" onclick="render('admissions')"><b>＋</b><span>New Admission</span></button><button class="quick-action" onclick="render('fees')"><b>₹</b><span>Add Fee</span></button><button class="quick-action" onclick="render('attendance')"><b>✓</b><span>Attendance</span></button><button class="quick-action" onclick="render('movement')"><b>↔</b><span>Entry / Exit</span></button></div></div>
   <div class="card"><div class="card-title-row"><h3>Important</h3><span>Needs attention</span></div><div class="quick-list"><div class="quick-item clickable" onclick="render('pending')"><span>Fee Pending Students</span><b>${pendingList.length}</b></div><div class="quick-item clickable" onclick="render('movement')"><span>Outside Students</span><b>${outsideList.length}</b></div><div class="quick-item clickable" onclick="render('movement')"><span>Late Returns</span><b>${late}</b></div><div class="quick-item clickable" onclick="render('notices')"><span>Urgent Notices</span><b>${notices}</b></div></div></div>
 </div>
 <div class="card"><div class="card-title-row"><h3>Recent Activity</h3><button class="text-btn" onclick="render('reports')">Reports →</button></div>${activities.length?`<div class="timeline">${activities.map(a=>`<div class="timeline-item"><i></i><div><b>${esc(a.details)}</b><span>${new Date(a.time).toLocaleString('en-IN')}</span></div></div>`).join('')}</div>`:'<div class="empty">No activity yet</div>'}</div>`;
 updateLiveClock();clearInterval(window._liveClockTimer);window._liveClockTimer=setInterval(updateLiveClock,1000);
}
function statCard(icon,label,value,sub,tone){return `<div class="stat stat-${tone}"><div class="stat-top"><span class="stat-icon">${icon}</span><span class="stat-arrow">↗</span></div><div class="label">${label}</div><div class="value">${value}</div><div class="stat-sub">${sub}</div></div>`}
window.dashboardStudentSearch=function(){const q=(el('dashboardSearch')?.value||'').trim().toLowerCase();if(!q)return alert('Student name, ID, phone లేదా seat enter చేయండి');const s=db.students.find(x=>[x.id,x.name,x.phone,x.parentPhone,x.seat].join(' ').toLowerCase().includes(q));if(!s)return alert('Student not found');viewStudent(s.id)}

function renderStudents(){el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="studentSearch" placeholder="Search name / phone / ID / seat"><select id="genderFilter"><option value="">All</option><option>Female</option><option>Male</option></select><button class="primary" onclick="showStudentForm()">+ Add Student</button></div><div id="studentsTable"></div></div>`;el('studentSearch').oninput=drawStudents;el('genderFilter').onchange=drawStudents;drawStudents()}
function avatar(s){return s.photo?`<img class="avatar" src="${s.photo}" alt="">`:`<span class="avatar">${esc((s.name||'?').slice(0,1).toUpperCase())}</span>`}
function drawStudents(){const q=(el('studentSearch')?.value||'').toLowerCase(),g=el('genderFilter')?.value||'';const list=db.students.filter(s=>(!g||s.gender===g)&&[s.id,s.name,s.phone,s.seat,s.course].join(' ').toLowerCase().includes(q));el('studentsTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Gender</th><th>Phone</th><th>Course / Batch</th><th>Seat</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td><div class="student-name">${avatar(s)}<b>${esc(s.name)}</b></div></td><td>${esc(s.id)}</td><td>${esc(s.gender)}</td><td>${esc(s.phone)}</td><td>${esc(s.course||'-')} / ${esc(s.batch||'-')}</td><td>${esc(s.seat||'-')}</td><td>${money(hallFee(s))}</td><td><span class="badge ${s.status==='Inactive'?'absent':'present'}">${esc(s.status||'Active')}</span></td><td><button class="secondary" onclick="viewStudent('${s.id}')">View</button> <button class="secondary" onclick="editStudent('${s.id}')">Edit</button> <button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students found</div>'}

function renderAdmissions(){el('pageContent').innerHTML=`<div class="card"><h3>New Student Admission</h3>${studentForm()}</div>`;bindStudentForm()}
function studentForm(s={}){return `<form id="studentForm" class="form-grid">
<div class="section-title">Student Details</div>
<div class="field"><label>Student ID *</label><input name="id" value="${esc(s.id||nextStudentId())}" required ${s.id?'readonly':''}></div>
<div class="field"><label>Full Name *</label><input name="name" value="${esc(s.name||'')}" required></div>
<div class="field"><label>Gender *</label><select name="gender"><option ${s.gender==='Female'?'selected':''}>Female</option><option ${s.gender==='Male'?'selected':''}>Male</option><option ${s.gender==='Other'?'selected':''}>Other</option></select></div>
<div class="field"><label>Date of Birth</label><input type="date" name="dob" value="${esc(s.dob||'')}"></div>
<div class="field"><label>Student Phone *</label><input name="phone" inputmode="numeric" value="${esc(s.phone||'')}" required></div>
<div class="field"><label>Photo</label><input id="photoInput" type="file" accept="image/*"></div>
<div class="field"><label>Photo Preview</label><img id="photoPreview" class="photo-preview" src="${s.photo||''}" alt=""></div>
<div class="section-title">Parent & Contact Details</div>
<div class="field"><label>Parent / Guardian Name</label><input name="parentName" value="${esc(s.parentName||'')}"></div>
<div class="field"><label>Parent Phone *</label><input name="parentPhone" inputmode="numeric" value="${esc(s.parentPhone||'')}" required></div>
<div class="field"><label>Emergency Phone</label><input name="emergencyPhone" inputmode="numeric" value="${esc(s.emergencyPhone||'')}"></div>
<div class="field span-3"><label>Address</label><textarea name="address">${esc(s.address||'')}</textarea></div>
<div class="section-title">Study Hall Details</div>
<div class="field"><label>Course / Exam</label><input name="course" value="${esc(s.course||'')}"></div>
<div class="field"><label>Batch / Timing</label><input name="batch" value="${esc(s.batch||'')}"></div>
<div class="field"><label>Seat Number</label><input name="seat" value="${esc(s.seat||'')}"></div>
<div class="field"><label>Joining Date</label><input type="date" name="joinDate" value="${esc(s.joinDate||today())}"></div>
<div class="field"><label>Monthly Fee</label><input type="number" name="monthlyFee" value="${hallFee(s)}"></div>
<div class="field"><label>ID Proof / Aadhaar (Optional)</label><input name="idProof" value="${esc(s.idProof||'')}"></div>
<div class="field"><label>Status</label><select name="status"><option ${s.status!=='Inactive'?'selected':''}>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></div>
<input type="hidden" name="photo" value="${s.photo||''}">
<div class="span-3 actions"><button class="primary" type="submit">Save Student</button><button type="button" class="secondary" onclick="render('students')">Cancel</button></div>
</form>`}
function bindStudentForm(editId=null){const form=el('studentForm'),photo=el('photoInput'),preview=el('photoPreview');if(photo)photo.onchange=()=>{const file=photo.files[0];if(!file)return;if(file.size>800000)return alert('Photo size 800 KB లోపు ఉండాలి.');const r=new FileReader();r.onload=()=>{form.elements.photo.value=r.result;preview.src=r.result};r.readAsDataURL(file)};form.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(form));o.monthlyFee=Number(o.monthlyFee||db.settings.monthlyFee);if(!/^\d{10}$/.test(o.phone.replace(/\D/g,'')))return alert('Student phone number 10 digits enter చేయండి');if(editId){db.students=db.students.map(s=>s.id===editId?o:s)}else{if(db.students.some(s=>s.id===o.id))return alert('Student ID already exists');db.students.push(o)}saveDB();closeModal();render('students');alert('Student saved successfully')}}
function nextStudentId(){let n=1;while(db.students.some(s=>s.id===`SN${String(n).padStart(3,'0')}`))n++;return `SN${String(n).padStart(3,'0')}`}
window.showStudentForm=()=>{openModal(`<h3>Add Student</h3>${studentForm()}`);bindStudentForm()};
window.editStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Edit Student</h3>${studentForm(s)}`);bindStudentForm(id)};
window.viewStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Student Profile</h3><div class="student-name">${avatar(s)}<div><h2 style="margin:0">${esc(s.name)}</h2><span class="muted">${esc(s.id)}</span></div></div><div class="card"><div class="form-grid"><div><b>Phone</b><p>${esc(s.phone||'-')}</p></div><div><b>Parent</b><p>${esc(s.parentName||'-')} / ${esc(s.parentPhone||'-')}</p></div><div><b>Course</b><p>${esc(s.course||'-')}</p></div><div><b>Batch</b><p>${esc(s.batch||'-')}</p></div><div><b>Seat</b><p>${esc(s.seat||'-')}</p></div><div><b>Monthly Fee</b><p>${money(hallFee(s))}</p></div><div class="span-3"><b>Address</b><p>${esc(s.address||'-')}</p></div></div></div>`)};
window.deleteStudent=id=>{if(confirm('Delete this student?')){db.students=db.students.filter(s=>s.id!==id);saveDB();drawStudents()}};

function studentOptions(){return db.students.filter(s=>s.status!=='Inactive').map(s=>`<option value="${s.id}">${esc(s.id)} - ${esc(s.name)}</option>`).join('')}
function renderFees(){el('pageContent').innerHTML=`<div class="card"><h3>Add Fee Payment</h3><form id="feeForm" class="form-grid"><div class="field"><label>Student</label><select id="feeStudent" name="studentId" required>${studentOptions()}</select></div><div class="field"><label>Month</label><input type="month" name="month" value="${monthNow()}" required></div><div class="field"><label>Monthly Fee</label><input id="feeAmount" type="number" name="amount" value="${db.settings.monthlyFee}" required></div><div class="field"><label>Paid Amount</label><input type="number" name="paid" required></div><div class="field"><label>Payment Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Payment Mode</label><select name="mode"><option>Cash</option><option>UPI</option><option>Bank</option></select></div><div class="span-3"><button class="primary">Save Payment</button></div></form></div><div class="card"><h3>Payment History</h3><div id="feeTable"></div></div>`;el('feeStudent').onchange=()=>{el('feeAmount').value=hallFee(db.students.find(s=>s.id===el('feeStudent').value))};el('feeStudent').dispatchEvent(new Event('change'));el('feeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.amount=Number(o.amount);o.paid=Number(o.paid);o.receipt='RC'+String(db.fees.length+1).padStart(4,'0');if(o.paid<=0||o.paid>o.amount)return alert('Paid amount సరైనదిగా నమోదు చేయండి');db.fees.push(o);logAction('fee_paid',`Fee received: ${studentName(o.studentId)} - ${money(o.paid)}`);saveDB();renderFees();alert('Fee payment saved')};drawFees()}
function drawFees(){const list=[...db.fees].reverse();el('feeTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Student</th><th>Month</th><th>Fee</th><th>Paid</th><th>Balance</th><th>Date</th><th>Mode</th><th></th></tr></thead><tbody>${list.map(f=>`<tr><td>${esc(f.receipt||'-')}</td><td>${esc(studentName(f.studentId))}</td><td>${esc(f.month)}</td><td>${money(f.amount)}</td><td>${money(f.paid)}</td><td>${money(Number(f.amount)-Number(f.paid))}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td><td><button class="danger" onclick="deleteFee('${f.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No payments</div>'}
window.deleteFee=id=>{if(confirm('Delete payment?')){db.fees=db.fees.filter(f=>f.id!==id);saveDB();renderFees()}};
function getPending(month=monthNow()){return db.students.filter(s=>s.status!=='Inactive').map(s=>{const paid=db.fees.filter(f=>f.studentId===s.id&&f.month===month).reduce((a,f)=>a+Number(f.paid||0),0),fee=hallFee(s);return {...s,paid,balance:Math.max(0,fee-paid),fee}}).filter(x=>x.balance>0)}
function renderPending(){el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="pendingMonth" type="month" value="${monthNow()}"><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div id="pendingTable"></div></div>`;el('pendingMonth').onchange=drawPending;drawPending()}
function drawPending(){const month=el('pendingMonth')?.value||monthNow(),list=getPending(month);el('pendingTable').innerHTML=`<h3>Pending Fee List - ${esc(month)}</h3>${list.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Phone</th><th>Fee</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${money(x.fee)}</td><td>${money(x.paid)}</td><td><b>${money(x.balance)}</b></td><td><span class="badge pending">Pending</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No pending fees</div>'}`}
window.downloadPendingPDF=()=>{const month=el('pendingMonth')?.value||monthNow(),list=getPending(month),{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(`${db.settings.hallName} - Pending Fee List`,14,18);doc.setFontSize(10);let y=30;doc.text('Month: '+month,14,y);y+=10;list.forEach((x,i)=>{doc.text(`${i+1}. ${x.id} - ${x.name} | Phone: ${x.phone} | Balance: Rs.${x.balance}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save(`Pending-Fees-${month}.pdf`)};

function renderAttendance(){const d=today();el('pageContent').innerHTML=`<div class="card"><h3>Attendance - ${d}</h3><div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.students.filter(s=>s.status!=='Inactive').map(s=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);return `<tr><td>${s.id}</td><td>${esc(s.name)}</td><td><span class="badge ${a?.status==='Present'?'present':a?.status==='Absent'?'absent':'pending'}">${a?.status||'Not Marked'}</span></td><td><button class="success" onclick="markAttendance('${s.id}','Present')">Present</button> <button class="danger" onclick="markAttendance('${s.id}','Absent')">Absent</button></td></tr>`}).join('')}</tbody></table></div></div>`}
window.markAttendance=(studentId,status)=>{db.attendance=db.attendance.filter(x=>!(x.studentId===studentId&&x.date===today()));db.attendance.push({studentId,date:today(),status,time:new Date().toLocaleTimeString()});logAction('attendance',`${studentName(studentId)} marked ${status}`);saveDB();renderAttendance()};
function renderMovement(){const outside=db.movements.filter(x=>x.status==='Outside');el('pageContent').innerHTML=`<div class="card"><h3>Student Going Out</h3><form id="moveForm" class="form-grid"><div class="field"><label>Student</label><select name="studentId">${studentOptions()}</select></div><div class="field"><label>Out Time</label><input type="datetime-local" name="outTime" value="${new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}"></div><div class="field"><label>Expected Return</label><input type="datetime-local" name="expectedReturn"></div><div class="field span-2"><label>Reason / Place</label><input name="reason" placeholder="Reason and place"></div><div class="field"><label>Google Maps Location Link</label><input name="location" placeholder="Paste Maps link"></div><div class="span-3"><button class="primary">Submit</button></div></form></div><div class="card"><h3>Currently Outside</h3>${outside.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Out Time</th><th>Expected Return</th><th>Reason / Location</th><th>Status</th><th>Action</th></tr></thead><tbody>${outside.map(x=>`<tr><td>${esc(studentName(x.studentId))}</td><td>${esc(x.outTime)}</td><td>${esc(x.expectedReturn||'-')}</td><td>${esc(x.reason||'-')} ${x.location?`<a target="_blank" rel="noopener" href="${esc(x.location)}">Open Map</a>`:''}</td><td><span class="badge outside">Outside</span></td><td><button class="success" onclick="markReturned('${x.id}')">Returned</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students outside</div>'}</div>`;el('moveForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.status='Outside';o.returnTime='';db.movements.push(o);logAction('went_out',`${studentName(o.studentId)} went outside`);saveDB();renderMovement()}}
window.markReturned=id=>{const x=db.movements.find(m=>m.id===id);if(x){x.status='Returned';x.returnTime=new Date().toISOString().slice(0,16);logAction('returned',`${studentName(x.studentId)} returned`);saveDB();renderMovement()}};
function renderReports(){el('pageContent').innerHTML=`<div class="grid stats"><div class="card"><h3>Student List</h3><p class="muted">All student details.</p><button class="primary" onclick="downloadStudentsPDF()">Download PDF</button></div><div class="card"><h3>Pending Fees</h3><p class="muted">Current month pending list.</p><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div class="card"><h3>Backup</h3><p class="muted">Download complete data backup.</p><button class="secondary" onclick="downloadBackup()">Download JSON</button></div><div class="card"><h3>Restore Backup</h3><p class="muted">Restore previously downloaded JSON.</p><input id="restoreFile" type="file" accept="application/json"><button class="secondary" onclick="restoreBackup()">Restore</button></div></div>`}
window.downloadStudentsPDF=()=>{const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(`${db.settings.hallName} - Student List`,14,18);doc.setFontSize(10);let y=30;db.students.forEach((s,i)=>{doc.text(`${i+1}. ${s.id} - ${s.name} | ${s.phone} | Seat: ${s.seat||'-'} | ${s.course||'-'}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save('Sri-Nidhi-Students.pdf')};
window.downloadBackup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='sri-nidhi-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.restoreBackup=()=>{const f=el('restoreFile').files[0];if(!f)return alert('Select backup file');const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.settings)throw Error();db=x;saveDB();alert('Backup restored');render('dashboard')}catch{alert('Invalid backup file')}};r.readAsText(f)};
function renderSettings(){el('pageContent').innerHTML=`<div class="card"><h3>Settings</h3><form id="settingsForm" class="form-grid"><div class="field"><label>Study Hall Name</label><input name="hallName" value="${esc(db.settings.hallName)}"></div><div class="field"><label>Default Monthly Fee</label><input type="number" name="monthlyFee" value="${db.settings.monthlyFee}"></div><div class="field"><label>Monthly Fee Due Day</label><input type="number" min="1" max="28" name="feeDueDay" value="${db.settings.feeDueDay||10}"></div><div class="field"><label>Admin Username</label><input name="adminUser" value="${esc(db.settings.adminUser)}"></div><div class="field"><label>Admin Password</label><input name="adminPass" value="${esc(db.settings.adminPass)}"></div><div class="span-3 actions"><button class="primary">Save Settings</button><button type="button" class="danger" onclick="resetDemo()">Reset Demo Data</button></div></form></div>`;el('settingsForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.monthlyFee=Number(o.monthlyFee);o.feeDueDay=Number(o.feeDueDay||10);db.settings=o;logAction('settings','Settings updated');saveDB();alert('Settings saved');render('dashboard')}}
window.resetDemo=()=>{if(confirm('Reset all data?')){db=clone(defaultDB);saveDB();render('dashboard')}};
window.render=render;

/* v1.3 stable feature layer */
db.notices=db.notices||[];db.diary=db.diary||[];saveDB();
function fmtDateTime(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN')}
function nextReceipt(){const nums=db.fees.map(f=>Number(String(f.receipt||'').replace(/\D/g,''))||0);return 'RC'+String(Math.max(0,...nums)+1).padStart(4,'0')}
function monthPaid(studentId,month){return db.fees.filter(f=>f.studentId===studentId&&f.month===month).reduce((a,f)=>a+Number(f.paid||0),0)}

window.viewStudent=function(id){const s=db.students.find(x=>x.id===id);if(!s)return;const fees=db.fees.filter(x=>x.studentId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const at=db.attendance.filter(x=>x.studentId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const mv=db.movements.filter(x=>x.studentId===id).sort((a,b)=>String(b.outTime).localeCompare(String(a.outTime)));openModal(`<h2>Student Master File</h2><div class="profile-head">${s.photo?`<img class="profile-photo" src="${s.photo}" alt="">`:`<div class="profile-photo">${esc((s.name||'?')[0])}</div>`}<div><h2 style="margin:0">${esc(s.name)}</h2><div class="muted">${esc(s.id)} • ${esc(s.course||'-')} • Seat ${esc(s.seat||'-')}</div><div class="actions" style="margin-top:10px"><button class="primary" onclick="downloadStudentProfilePDF('${s.id}')">Profile PDF</button><button class="secondary" onclick="editStudent('${s.id}');closeModal()">Edit</button></div></div></div><div class="profile-grid">${[['Phone',s.phone],['Parent',s.parentName],['Parent Phone',s.parentPhone],['Emergency',s.emergencyPhone],['Gender',s.gender],['DOB',s.dob],['Batch',s.batch],['Join Date',s.joinDate],['Monthly Fee',money(hallFee(s))],['Status',s.status],['Address',s.address],['ID Proof',s.idProof]].map(x=>`<div class="profile-field"><small>${x[0]}</small><b>${esc(x[1]||'-')}</b></div>`).join('')}</div><div class="card"><h3>Fee History</h3>${fees.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Month</th><th>Paid</th><th>Date</th><th>Mode</th></tr></thead><tbody>${fees.map(f=>`<tr><td>${esc(f.receipt)}</td><td>${esc(f.month)}</td><td>${money(f.paid)}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No fee history</div>'}</div><div class="card"><h3>Attendance History</h3>${at.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Time</th></tr></thead><tbody>${at.slice(0,60).map(a=>`<tr><td>${esc(a.date)}</td><td>${esc(a.status)}</td><td>${esc(a.time||'-')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No attendance history</div>'}</div><div class="card"><h3>Entry / Exit History</h3>${mv.length?`<div class="table-wrap"><table><thead><tr><th>Out</th><th>Expected</th><th>Returned</th><th>Reason</th><th>Status</th></tr></thead><tbody>${mv.slice(0,40).map(m=>`<tr><td>${esc(fmtDateTime(m.outTime))}</td><td>${esc(fmtDateTime(m.expectedReturn))}</td><td>${esc(fmtDateTime(m.returnTime))}</td><td>${esc(m.reason||'-')}</td><td>${esc(m.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No movement history</div>'}</div>`)}
window.downloadStudentProfilePDF=function(id){const s=db.students.find(x=>x.id===id);if(!s)return;const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(17);doc.text(db.settings.hallName,14,18);doc.setFontSize(13);doc.text('Student Master Profile',14,27);doc.setFontSize(10);let y=40;const rows=[['Student ID',s.id],['Name',s.name],['Gender',s.gender],['Phone',s.phone],['Parent',s.parentName],['Parent Phone',s.parentPhone],['Emergency',s.emergencyPhone],['Course / Batch',`${s.course||'-'} / ${s.batch||'-'}`],['Seat',s.seat],['Join Date',s.joinDate],['Monthly Fee',`Rs.${hallFee(s)}`],['Status',s.status],['Address',s.address]];rows.forEach(r=>{doc.text(`${r[0]}: ${r[1]||'-'}`,14,y);y+=8});y+=4;doc.setFontSize(12);doc.text('Recent Fee History',14,y);y+=8;doc.setFontSize(9);db.fees.filter(f=>f.studentId===id).slice(-12).reverse().forEach(f=>{doc.text(`${f.receipt} | ${f.month} | Rs.${f.paid} | ${f.date} | ${f.mode}`,14,y);y+=7});doc.save(`${s.id}-${s.name}-Profile.pdf`)}

function renderFees(){const active=db.students.filter(s=>s.status!=='Inactive');el('pageContent').innerHTML=`<div class="card"><h3>Collect Monthly Fee</h3><form id="feeForm" class="form-grid"><div class="field"><label>Student</label><select id="feeStudent" name="studentId" required>${active.map(s=>`<option value="${s.id}">${esc(s.id)} - ${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Month</label><input id="feeMonth" type="month" name="month" value="${monthNow()}" required></div><div class="field"><label>Monthly Fee</label><input id="feeAmount" type="number" name="amount" readonly></div><div class="field"><label>Already Paid</label><input id="alreadyPaid" type="number" readonly></div><div class="field"><label>Balance</label><input id="feeBalance" type="number" readonly></div><div class="field"><label>Pay Now</label><input id="payNow" type="number" name="paid" required></div><div class="field"><label>Payment Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Payment Mode</label><select name="mode"><option>Cash</option><option>UPI</option><option>Bank</option></select></div><div class="field"><label>Transaction / Note</label><input name="reference" placeholder="Optional"></div><div class="span-3"><button class="primary">Save & Generate Receipt</button></div></form></div><div class="card"><h3>Payment History</h3><div id="feeTable"></div></div>`;const refresh=()=>{const sid=el('feeStudent').value,m=el('feeMonth').value,s=db.students.find(x=>x.id===sid),amount=hallFee(s),paid=monthPaid(sid,m),bal=Math.max(0,amount-paid);el('feeAmount').value=amount;el('alreadyPaid').value=paid;el('feeBalance').value=bal;el('payNow').value=bal||'';el('payNow').max=bal};el('feeStudent').onchange=refresh;el('feeMonth').onchange=refresh;refresh();el('feeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),balance=Number(el('feeBalance').value);o.id=uid();o.amount=Number(o.amount);o.paid=Number(o.paid);if(balance<=0)return alert('ఈ నెల fee ఇప్పటికే పూర్తిగా చెల్లించారు');if(o.paid<=0||o.paid>balance)return alert(`Pay Now amount ₹1 నుండి ${money(balance)} మధ్య ఉండాలి`);o.receipt=nextReceipt();db.fees.push(o);logAction('fee_paid',`Fee received: ${studentName(o.studentId)} - ${money(o.paid)} (${o.receipt})`);saveDB();downloadReceiptPDF(o.id);renderFees()};drawFees()}
function drawFees(){const list=[...db.fees].reverse();el('feeTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Student</th><th>Month</th><th>Paid</th><th>Date</th><th>Mode</th><th>Actions</th></tr></thead><tbody>${list.map(f=>`<tr><td>${esc(f.receipt||'-')}</td><td>${esc(studentName(f.studentId))}</td><td>${esc(f.month)}</td><td>${money(f.paid)}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td><td class="receipt-actions"><button class="secondary" onclick="downloadReceiptPDF('${f.id}')">Receipt</button><button class="danger" onclick="deleteFee('${f.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No payments</div>'}
window.downloadReceiptPDF=function(id){const f=db.fees.find(x=>x.id===id),s=f&&db.students.find(x=>x.id===f.studentId);if(!f||!s)return;const {jsPDF}=window.jspdf,doc=new jsPDF({format:'a5'});doc.setFontSize(17);doc.text(db.settings.hallName,74,18,{align:'center'});doc.setFontSize(11);doc.text('FEE RECEIPT',74,27,{align:'center'});doc.line(12,32,136,32);doc.setFontSize(10);const rows=[['Receipt No',f.receipt],['Date',f.date],['Student ID',s.id],['Student Name',s.name],['Month',f.month],['Monthly Fee',`Rs.${f.amount}`],['Paid Now',`Rs.${f.paid}`],['Payment Mode',f.mode],['Reference',f.reference||'-'],['Total Paid for Month',`Rs.${monthPaid(s.id,f.month)}`],['Balance',`Rs.${Math.max(0,hallFee(s)-monthPaid(s.id,f.month))}`]];let y=43;rows.forEach(r=>{doc.text(r[0],16,y);doc.text(': '+String(r[1]),60,y);y+=9});doc.line(12,y+2,136,y+2);doc.text('Authorized Signature',92,y+18);doc.save(`${f.receipt}-${s.name}.pdf`)}

function renderAttendance(){const d=window._attendanceDate||today();el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="attendanceDate" type="date" value="${d}"><button class="success" onclick="markAllAttendance('Present')">Mark All Present</button><button class="danger" onclick="markAllAttendance('Absent')">Mark All Absent</button><button class="secondary" onclick="downloadAttendancePDF()">Day PDF</button></div><div id="attendanceTable"></div></div><div class="card"><h3>Monthly Attendance Summary</h3><div class="toolbar"><input id="attendanceMonth" type="month" value="${d.slice(0,7)}"><button class="primary" onclick="downloadMonthlyAttendancePDF()">Monthly PDF</button></div><div id="attendanceSummary"></div></div>`;el('attendanceDate').onchange=e=>{window._attendanceDate=e.target.value;renderAttendance()};el('attendanceMonth').onchange=drawAttendanceSummary;drawAttendanceDay();drawAttendanceSummary()}
function drawAttendanceDay(){const d=el('attendanceDate').value,students=db.students.filter(s=>s.status!=='Inactive');el('attendanceTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>${students.map(s=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);return `<tr><td>${s.id}</td><td>${esc(s.name)}</td><td><span class="badge ${a?.status==='Present'?'present':a?.status==='Absent'?'absent':'pending'}">${a?.status||'Not Marked'}</span></td><td><button class="success" onclick="markAttendanceForDate('${s.id}','Present','${d}')">Present</button> <button class="danger" onclick="markAttendanceForDate('${s.id}','Absent','${d}')">Absent</button></td></tr>`}).join('')}</tbody></table></div>`}
window.markAttendanceForDate=(studentId,status,date)=>{db.attendance=db.attendance.filter(x=>!(x.studentId===studentId&&x.date===date));db.attendance.push({studentId,date,status,time:new Date().toLocaleTimeString()});logAction('attendance',`${studentName(studentId)} marked ${status} on ${date}`);saveDB();drawAttendanceDay();drawAttendanceSummary()};window.markAllAttendance=status=>{const d=el('attendanceDate').value;db.students.filter(s=>s.status!=='Inactive').forEach(s=>{db.attendance=db.attendance.filter(x=>!(x.studentId===s.id&&x.date===d));db.attendance.push({studentId:s.id,date:d,status,time:new Date().toLocaleTimeString()})});logAction('attendance_bulk',`All students marked ${status} on ${d}`);saveDB();drawAttendanceDay();drawAttendanceSummary()}
function drawAttendanceSummary(){const m=el('attendanceMonth').value,list=db.students.filter(s=>s.status!=='Inactive').map(s=>{const a=db.attendance.filter(x=>x.studentId===s.id&&x.date.startsWith(m));return {s,p:a.filter(x=>x.status==='Present').length,a:a.filter(x=>x.status==='Absent').length}});el('attendanceSummary').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Present</th><th>Absent</th><th>Marked Days</th></tr></thead><tbody>${list.map(x=>`<tr><td>${x.s.id}</td><td>${esc(x.s.name)}</td><td>${x.p}</td><td>${x.a}</td><td>${x.p+x.a}</td></tr>`).join('')}</tbody></table></div>`}
window.downloadAttendancePDF=()=>{const d=el('attendanceDate').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(15);doc.text(`${db.settings.hallName} - Attendance`,14,18);doc.setFontSize(10);doc.text(`Date: ${d}`,14,27);let y=38;db.students.filter(s=>s.status!=='Inactive').forEach((s,i)=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);doc.text(`${i+1}. ${s.id} - ${s.name} - ${a?.status||'Not Marked'}`,14,y);y+=7;if(y>282){doc.addPage();y=18}});doc.save(`Attendance-${d}.pdf`)}
window.downloadMonthlyAttendancePDF=()=>{const m=el('attendanceMonth').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(15);doc.text(`${db.settings.hallName} - Monthly Attendance`,14,18);doc.setFontSize(10);doc.text(`Month: ${m}`,14,27);let y=38;db.students.filter(s=>s.status!=='Inactive').forEach((s,i)=>{const a=db.attendance.filter(x=>x.studentId===s.id&&x.date.startsWith(m)),p=a.filter(x=>x.status==='Present').length,ab=a.filter(x=>x.status==='Absent').length;doc.text(`${i+1}. ${s.id} - ${s.name} | Present: ${p} | Absent: ${ab}`,14,y);y+=7;if(y>282){doc.addPage();y=18}});doc.save(`Monthly-Attendance-${m}.pdf`)}

function renderNotices(){const list=[...(db.notices||[])].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));el('pageContent').innerHTML=`<div class="card"><h3>Add Notice</h3><form id="noticeForm" class="form-grid"><div class="field span-2"><label>Title</label><input name="title" required></div><div class="field"><label>Priority</label><select name="priority"><option>Normal</option><option>Urgent</option></select></div><div class="field span-3"><label>Notice</label><textarea name="message" required></textarea></div><div class="span-3"><button class="primary">Publish Notice</button></div></form></div><div class="card"><h3>Notice Board</h3>${list.length?list.map(n=>`<div class="notice-card ${n.priority==='Urgent'?'urgent':''}"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(n.title)}</b><button class="danger" onclick="deleteNotice('${n.id}')">Delete</button></div><p>${esc(n.message)}</p><small class="muted">${fmtDateTime(n.createdAt)} • ${esc(n.priority)}</small></div>`).join(''):'<div class="empty">No notices</div>'}</div>`;el('noticeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.createdAt=new Date().toISOString();db.notices.push(o);logAction('notice',`Notice published: ${o.title}`);saveDB();renderNotices()}}
window.deleteNotice=id=>{if(confirm('Delete notice?')){db.notices=db.notices.filter(x=>x.id!==id);saveDB();renderNotices()}}
function renderDiary(){const d=window._diaryDate||today(),entry=db.diary.find(x=>x.date===d)||{};el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="diaryDate" type="date" value="${d}"><button class="secondary" onclick="downloadDailyClosingPDF()">Closing Report PDF</button></div><form id="diaryForm" class="form-grid"><div class="field span-3"><label>Important Notes</label><textarea name="notes" placeholder="Admissions, visitors, complaints, special events...">${esc(entry.notes||'')}</textarea></div><div class="field"><label>Cash Expenses</label><input type="number" name="expenses" value="${Number(entry.expenses||0)}"></div><div class="field span-2"><label>Expense Details</label><input name="expenseDetails" value="${esc(entry.expenseDetails||'')}"></div><div class="span-3"><button class="primary">Save Daily Diary</button></div></form></div><div class="card"><h3>Automatic Day Summary</h3><div id="dailySummary" class="diary-summary"></div></div>`;el('diaryDate').onchange=e=>{window._diaryDate=e.target.value;renderDiary()};el('diaryForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.date=d;o.expenses=Number(o.expenses||0);o.updatedAt=new Date().toISOString();db.diary=db.diary.filter(x=>x.date!==d);db.diary.push(o);logAction('diary',`Daily diary saved for ${d}`);saveDB();renderDiary()};el('dailySummary').textContent=buildDailySummary(d)}
function buildDailySummary(d){const admissions=db.students.filter(s=>s.joinDate===d).length,fees=db.fees.filter(f=>f.date===d),collection=fees.reduce((a,f)=>a+Number(f.paid||0),0),present=db.attendance.filter(a=>a.date===d&&a.status==='Present').length,absent=db.attendance.filter(a=>a.date===d&&a.status==='Absent').length,out=db.movements.filter(m=>String(m.outTime||'').startsWith(d)).length,returned=db.movements.filter(m=>String(m.returnTime||'').startsWith(d)).length,entry=db.diary.find(x=>x.date===d)||{};return `Date: ${d}\nNew Admissions: ${admissions}\nFee Transactions: ${fees.length}\nFee Collection: ${money(collection)}\nPresent: ${present}\nAbsent: ${absent}\nWent Outside: ${out}\nReturned: ${returned}\nExpenses: ${money(entry.expenses||0)}\nNet Cash Position: ${money(collection-Number(entry.expenses||0))}\n\nNotes: ${entry.notes||'-'}\nExpense Details: ${entry.expenseDetails||'-'}`}
window.downloadDailyClosingPDF=()=>{const d=el('diaryDate').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(db.settings.hallName,14,18);doc.setFontSize(12);doc.text('Daily Closing Report',14,27);doc.setFontSize(10);const lines=doc.splitTextToSize(buildDailySummary(d),180);doc.text(lines,14,40);doc.save(`Daily-Closing-${d}.pdf`)}

function renderReports(){el('pageContent').innerHTML=`<div class="grid stats"><div class="card"><h3>Student List</h3><p class="muted">All active and inactive students.</p><button class="primary" onclick="downloadStudentsPDF()">Download PDF</button></div><div class="card"><h3>Pending Fees</h3><p class="muted">Current month pending list.</p><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div class="card"><h3>Daily Closing</h3><p class="muted">Today collection, attendance and movement.</p><button class="primary" onclick="render('diary')">Open Diary</button></div><div class="card"><h3>Backup</h3><p class="muted">Complete local database backup.</p><button class="secondary" onclick="downloadBackup()">Download JSON</button></div><div class="card"><h3>Restore Backup</h3><p class="muted">Restore a valid Sri Nidhi backup.</p><input id="restoreFile" type="file" accept="application/json"><button class="secondary" onclick="restoreBackup()">Restore</button></div><div class="card"><h3>Install as App</h3><p class="muted">Chrome menu → Add to Home screen.</p><div class="install-tip">Works after GitHub Pages deployment.</div></div></div>`}
