const DB_KEY='sriNidhiStudyHallV12';
const defaultDB={
 meta:{schemaVersion:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},
 settings:{hallName:'Sri Nidhi Study Hall',monthlyFee:1500,feeDueDay:10,adminUser:'admin',adminPass:'1234'},
 students:[
  {id:'SN0001',name:'Anusha',gender:'Female',dob:'',phone:'9876543210',parentName:'',parentPhone:'9123456780',emergencyPhone:'',address:'',course:'DSC',batch:'Morning',seat:'G-01',joinDate:'2026-07-01',monthlyFee:1500,idProof:'',status:'Active',photo:''},
  {id:'SN0002',name:'Kavya',gender:'Female',dob:'',phone:'9876501234',parentName:'',parentPhone:'9012345678',emergencyPhone:'',address:'',course:'TET',batch:'Morning',seat:'G-02',joinDate:'2026-07-03',monthlyFee:1500,idProof:'',status:'Active',photo:''},
  {id:'SN0003',name:'Ramesh',gender:'Male',dob:'',phone:'9866001122',parentName:'',parentPhone:'9000011111',emergencyPhone:'',address:'',course:'Police',batch:'Evening',seat:'B-01',joinDate:'2026-07-05',monthlyFee:1500,idProof:'',status:'Active',photo:''}
 ],
 fees:[
  {id:uid(),studentId:'SN0001',month:'2026-07',amount:1500,paid:1500,date:'2026-07-05',mode:'UPI',receipt:'RC001'},
  {id:uid(),studentId:'SN0002',month:'2026-07',amount:1500,paid:500,date:'2026-07-06',mode:'Cash',receipt:'RC002'}
 ], attendance:[], movements:[], audit:[]
};
let db=loadDB(), currentPage='dashboard';
function uid(){return (crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2))}
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadDB(){
 try{
  const raw=localStorage.getItem(DB_KEY), data=raw?JSON.parse(raw):clone(defaultDB);
  data.meta=data.meta||{schemaVersion:2,createdAt:new Date().toISOString()};
  data.settings={...clone(defaultDB.settings),...(data.settings||{})};
  for(const key of ['students','fees','attendance','movements','audit','notices','diary']) if(!Array.isArray(data[key])) data[key]=[];
  return data;
 }catch{return clone(defaultDB)}
}
function saveDB(){
 try{db.meta=db.meta||{};db.meta.schemaVersion=2;db.meta.updatedAt=new Date().toISOString();localStorage.setItem(DB_KEY,JSON.stringify(db));return true}
 catch(e){alert('Data save కాలేదు. Photo size తగ్గించి మళ్లీ ప్రయత్నించండి.');return false}
}
function logAction(type,details){db.audit=db.audit||[];db.audit.unshift({id:uid(),type,details,time:new Date().toISOString()});db.audit=db.audit.slice(0,250)}
function el(id){return document.getElementById(id)}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
function today(){return new Date().toISOString().slice(0,10)}
function monthNow(){return new Date().toISOString().slice(0,7)}
function studentName(id){return db.students.find(s=>s.id===id)?.name||id}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function hallFee(s){return Number(s?.monthlyFee||db.settings.monthlyFee||0)}
function validPhone(v){return !v||/^[6-9]\d{9}$/.test(String(v).trim())}
function isLateMovement(m){return m.status==='Outside'&&m.expectedReturn&&new Date(m.expectedReturn).getTime()<Date.now()}
function closeMenu(){el('sidebar').classList.remove('open');el('overlay').classList.add('hidden')}
function openMenu(){el('sidebar').classList.add('open');el('overlay').classList.remove('hidden')}

el('todayText').textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
el('loginBtn').onclick=()=>{const u=el('loginUser').value.trim(),p=el('loginPass').value;if(u===db.settings.adminUser&&p===db.settings.adminPass){el('loginView').classList.add('hidden');el('appView').classList.remove('hidden');history.replaceState({page:'dashboard'},'',location.href);render('dashboard',false)}else el('loginError').textContent='Wrong username or password'};
el('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')el('loginBtn').click()});
el('logoutBtn').onclick=()=>location.reload();
el('menuBtn').onclick=()=>el('sidebar').classList.contains('open')?closeMenu():openMenu();
el('overlay').onclick=closeMenu;
el('navMenu').onclick=e=>{const b=e.target.closest('button[data-page]');if(!b)return;render(b.dataset.page);closeMenu()};
el('modalClose').onclick=closeModal;el('modal').onclick=e=>{if(e.target===el('modal'))closeModal()};
function openModal(html){el('modalBody').innerHTML=html;el('modal').classList.remove('hidden')}
function closeModal(){el('modal').classList.add('hidden');el('modalBody').innerHTML=''}

function render(page,pushHistory=true){currentPage=page;document.querySelectorAll('#navMenu button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={dashboard:'Home',students:'Students',admissions:'Admissions',fees:'Fees',pending:'Pending Fees',attendance:'Attendance',movement:'Entry / Exit',notices:'Notices',diary:'Daily Diary',dailyupdates:'Daily Updates',reports:'Reports',settings:'Settings'};el('pageTitle').textContent=titles[page]||page;el('sideHallName').textContent=db.settings.hallName.replace(/Study Hall/i,'').trim()||'Sri Nidhi';if(pushHistory&&page!==history.state?.page)history.pushState({page},'',location.href);({dashboard:renderDashboard,students:renderStudents,admissions:renderAdmissions,fees:renderFees,pending:renderPending,attendance:renderAttendance,movement:renderMovement,notices:renderNotices,diary:renderDiary,dailyupdates:renderDailyUpdates,reports:renderReports,settings:renderSettings}[page]||renderDashboard)()}
window.addEventListener('popstate',e=>{if(!el('modal').classList.contains('hidden')){closeModal();history.pushState({page:currentPage},'',location.href);return}if(!el('appView').classList.contains('hidden')){const target=e.state?.page||'dashboard';render(target,false)}});

function updateLiveClock(){const clock=el('liveClock');if(clock)clock.textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function renderDashboard(){
 const content=el('pageContent');
 content.innerHTML=`
 <section class="home-welcome">
   <p>WELCOME BACK</p>
   <h1>${esc(db.settings.hallName)}</h1>
   <span>Student Management, Fees & Security</span>
 </section>
 <section class="home-menu-list" aria-label="Main modules">
   ${homeCard('students','Students')}
   ${homeCard('admissions','Admissions')}
   ${homeCard('attendance','Attendance')}
   ${homeCard('movement','Entry / Exit')}
   ${homeCard('notices','Notices')}
   ${homeCard('diary','Daily Diary')}
   ${homeCard('dailyupdates','Daily Updates')}
   ${homeCard('fees','Fees')}
   ${homeCard('pending','Pending Fees')}
   ${homeCard('reports','Reports')}
   ${homeCard('settings','Settings')}
 </section>`;
}
function homeCard(page,label){return `<button class="home-menu-card" onclick="render('${page}')"><span>${label}</span><b aria-hidden="true">›</b></button>`}

function renderDailyUpdates(){
 const t=today(), active=db.students.filter(s=>s.status!=='Inactive');
 const admissions=active.filter(s=>s.joinDate===t).length;
 const feesToday=db.fees.filter(f=>f.date===t); const collected=feesToday.reduce((a,f)=>a+Number(f.paid||0),0);
 const present=db.attendance.filter(a=>a.date===t&&a.status==='Present').length;
 const absent=db.attendance.filter(a=>a.date===t&&a.status==='Absent').length;
 const outside=db.movements.filter(m=>m.status==='Outside');
 const late=outside.filter(isLateMovement);
 const notices=(db.notices||[]).filter(n=>(n.date||'')===t).length;
 const diary=(db.diary||[]).find(d=>d.date===t);
 el('pageContent').innerHTML=`<div class="daily-grid">
   ${dailyCard('Today Admissions',admissions,'admissions')}
   ${dailyCard('Fees Collected',money(collected),'fees')}
   ${dailyCard('Present',present,'attendance')}
   ${dailyCard('Absent',absent,'attendance')}
   ${dailyCard('Students Outside',outside.length,'movement')}
   ${dailyCard('Not Returned',late.length,'movement',late.length?'alert':'')}
   ${dailyCard('Today Notices',notices,'notices')}
   ${dailyCard('Diary Status',diary?'Updated':'Not Updated','diary')}
 </div>`;
}
function dailyCard(label,value,page,cls=''){return `<button class="daily-card ${cls}" onclick="render('${page}')"><span>${label}</span><b>${value}</b><small>Open ›</small></button>`}

function overviewRow(label,value){return `<div class="d3-row"><span>${label}</span><b>${value}</b></div>`}
function importantRow(label,value,page){return `<button class="d3-row d3-row-button" onclick="render('${page}')"><span>${label}</span><b>${value}</b></button>`}
window.dashboardStudentSearch=function(){const q=(el('dashboardSearch')?.value||'').trim().toLowerCase();if(!q)return alert('Student name, ID, phone లేదా parent name enter చేయండి');const s=db.students.find(x=>[x.id,x.name,x.phone,x.parentName,x.parentPhone,x.course,x.batch].join(' ').toLowerCase().includes(q));if(!s)return alert('Student not found');viewStudent(s.id)}

function renderStudents(){el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="studentSearch" placeholder="Search name / phone / ID / parent"><select id="genderFilter"><option value="">All</option><option>Female</option><option>Male</option></select><button class="primary" onclick="showStudentForm()">+ Add Student</button></div><div id="studentsTable"></div></div>`;el('studentSearch').oninput=drawStudents;el('genderFilter').onchange=drawStudents;drawStudents()}
function avatar(s){return s.photo?`<img class="avatar" src="${s.photo}" alt="">`:`<span class="avatar">${esc((s.name||'?').slice(0,1).toUpperCase())}</span>`}
function drawStudents(){const q=(el('studentSearch')?.value||'').toLowerCase(),g=el('genderFilter')?.value||'';const list=db.students.filter(s=>(!g||s.gender===g)&&[s.id,s.name,s.phone,s.parentName,s.parentPhone,s.course,s.batch].join(' ').toLowerCase().includes(q));el('studentsTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Gender</th><th>Phone</th><th>Course / Batch</th><th>Parent</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td><div class="student-name">${avatar(s)}<b>${esc(s.name)}</b></div></td><td>${esc(s.id)}</td><td>${esc(s.gender)}</td><td>${esc(s.phone)}</td><td>${esc(s.course||'-')} / ${esc(s.batch||'-')}</td><td>${esc(s.parentName||'-')}</td><td>${money(hallFee(s))}</td><td><span class="badge ${s.status==='Inactive'?'absent':'present'}">${esc(s.status||'Active')}</span></td><td><button class="secondary" onclick="viewStudent('${s.id}')">View</button> <button class="secondary" onclick="editStudent('${s.id}')">Edit</button> <button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students found</div>'}

function renderAdmissions(){el('pageContent').innerHTML=`<div class="card"><h3>New Student Admission</h3>${studentForm()}</div>`;bindStudentForm()}
function studentForm(s={}){return `<form id="studentForm" class="form-grid">
<div class="section-title">Student Details</div>
<div class="field"><label>Student ID *</label><input name="id" value="${esc(s.id||nextStudentId())}" required ${s.id?'readonly':''}></div>
<div class="field"><label>Full Name *</label><input name="name" value="${esc(s.name||'')}" required></div>
<div class="field"><label>Gender *</label><select name="gender"><option ${s.gender==='Female'?'selected':''}>Female</option><option ${s.gender==='Male'?'selected':''}>Male</option><option ${s.gender==='Other'?'selected':''}>Other</option></select></div>
<div class="field"><label>Date of Birth</label><input type="date" name="dob" value="${esc(s.dob||'')}"></div>
<div class="field"><label>Student Phone *</label><input name="phone" inputmode="numeric" value="${esc(s.phone||'')}" required></div>
<div class="field"><label>Photo</label><input id="photoInput" type="file" accept="image/*"></div>
<div class="field"><label>Photo Preview</label><img id="photoPreview" class="photo-preview" src="${s.photo||''}" alt=""></div>
<div class="section-title">Parent & Contact Details</div>
<div class="field"><label>Parent / Guardian Name</label><input name="parentName" value="${esc(s.parentName||'')}"></div>
<div class="field"><label>Parent Phone *</label><input name="parentPhone" inputmode="numeric" value="${esc(s.parentPhone||'')}" required></div>
<div class="field"><label>Emergency Phone</label><input name="emergencyPhone" inputmode="numeric" value="${esc(s.emergencyPhone||'')}"></div>
<div class="field span-3"><label>Address</label><textarea name="address">${esc(s.address||'')}</textarea></div>
<div class="section-title">Study Hall Details</div>
<div class="field"><label>Course / Exam</label><input name="course" value="${esc(s.course||'')}"></div>
<div class="field"><label>Batch / Timing</label><input name="batch" value="${esc(s.batch||'')}"></div>
<div class="field"><label>Seat Number (Optional)</label><input name="seat" value="${esc(s.seat||'')}"></div>
<div class="field"><label>Joining Date</label><input type="date" name="joinDate" value="${esc(s.joinDate||today())}"></div>
<div class="field"><label>Monthly Fee</label><input type="number" name="monthlyFee" value="${hallFee(s)}"></div>
<div class="field"><label>ID Proof / Aadhaar (Optional)</label><input name="idProof" value="${esc(s.idProof||'')}"></div>
<div class="field"><label>Status</label><select name="status"><option ${s.status!=='Inactive'?'selected':''}>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></div>
<input type="hidden" name="photo" value="${s.photo||''}">
<div class="span-3 actions"><button class="primary" type="submit">Save Student</button><button type="button" class="secondary" onclick="render('students')">Cancel</button></div>
</form>`}
function bindStudentForm(editId=null){const form=el('studentForm'),photo=el('photoInput'),preview=el('photoPreview');if(photo)photo.onchange=()=>{const file=photo.files[0];if(!file)return;if(file.size>800000)return alert('Photo size 800 KB లోపు ఉండాలి.');const r=new FileReader();r.onload=()=>{form.elements.photo.value=r.result;preview.src=r.result};r.readAsDataURL(file)};form.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(form));o.monthlyFee=Number(o.monthlyFee||db.settings.monthlyFee);if(!/^\d{10}$/.test(o.phone.replace(/\D/g,'')))return alert('Student phone number 10 digits enter చేయండి');if(editId){db.students=db.students.map(s=>s.id===editId?o:s)}else{if(db.students.some(s=>s.id===o.id))return alert('Student ID already exists');db.students.push(o)}saveDB();closeModal();render('students');alert('Student saved successfully')}}
function nextStudentId(){let n=1;while(db.students.some(s=>s.id===`SN${String(n).padStart(4,'0')}`))n++;return `SN${String(n).padStart(4,'0')}`}
window.showStudentForm=()=>{openModal(`<h3>Add Student</h3>${studentForm()}`);bindStudentForm()};
window.editStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Edit Student</h3>${studentForm(s)}`);bindStudentForm(id)};
window.viewStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Student Profile</h3><div class="student-name">${avatar(s)}<div><h2 style="margin:0">${esc(s.name)}</h2><span class="muted">${esc(s.id)}</span></div></div><div class="card"><div class="form-grid"><div><b>Phone</b><p>${esc(s.phone||'-')}</p></div><div><b>Parent</b><p>${esc(s.parentName||'-')} / ${esc(s.parentPhone||'-')}</p></div><div><b>Course</b><p>${esc(s.course||'-')}</p></div><div><b>Batch</b><p>${esc(s.batch||'-')}</p></div><div><b>Seat</b><p>${esc(s.seat||'-')}</p></div><div><b>Monthly Fee</b><p>${money(hallFee(s))}</p></div><div class="span-3"><b>Address</b><p>${esc(s.address||'-')}</p></div></div></div>`)};
window.deleteStudent=id=>{const s=db.students.find(x=>x.id===id);if(!s)return;if(confirm(`Delete ${s.name}? Fee, attendance and movement history will remain in reports.`)){db.students=db.students.filter(x=>x.id!==id);logAction('student_deleted',`${s.id} - ${s.name} deleted`);saveDB();drawStudents()}};

function studentOptions(){return db.students.filter(s=>s.status!=='Inactive').map(s=>`<option value="${s.id}">${esc(s.id)} - ${esc(s.name)}</option>`).join('')}
function renderFees(){el('pageContent').innerHTML=`<div class="card"><h3>Add Fee Payment</h3><form id="feeForm" class="form-grid"><div class="field"><label>Student</label><select id="feeStudent" name="studentId" required>${studentOptions()}</select></div><div class="field"><label>Month</label><input type="month" name="month" value="${monthNow()}" required></div><div class="field"><label>Monthly Fee</label><input id="feeAmount" type="number" name="amount" value="${db.settings.monthlyFee}" required></div><div class="field"><label>Paid Amount</label><input type="number" name="paid" required></div><div class="field"><label>Payment Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Payment Mode</label><select name="mode"><option>Cash</option><option>UPI</option><option>Bank</option></select></div><div class="span-3"><button class="primary">Save Payment</button></div></form></div><div class="card"><h3>Payment History</h3><div id="feeTable"></div></div>`;el('feeStudent').onchange=()=>{el('feeAmount').value=hallFee(db.students.find(s=>s.id===el('feeStudent').value))};el('feeStudent').dispatchEvent(new Event('change'));el('feeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.amount=Number(o.amount);o.paid=Number(o.paid);o.receipt='RC'+String(db.fees.length+1).padStart(4,'0');if(o.paid<=0||o.paid>o.amount)return alert('Paid amount సరైనదిగా నమోదు చేయండి');db.fees.push(o);logAction('fee_paid',`Fee received: ${studentName(o.studentId)} - ${money(o.paid)}`);saveDB();renderFees();alert('Fee payment saved')};drawFees()}
function drawFees(){const list=[...db.fees].reverse();el('feeTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Student</th><th>Month</th><th>Fee</th><th>Paid</th><th>Balance</th><th>Date</th><th>Mode</th><th></th></tr></thead><tbody>${list.map(f=>`<tr><td>${esc(f.receipt||'-')}</td><td>${esc(studentName(f.studentId))}</td><td>${esc(f.month)}</td><td>${money(f.amount)}</td><td>${money(f.paid)}</td><td>${money(Number(f.amount)-Number(f.paid))}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td><td><button class="danger" onclick="deleteFee('${f.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No payments</div>'}
window.deleteFee=id=>{if(confirm('Delete payment?')){db.fees=db.fees.filter(f=>f.id!==id);saveDB();renderFees()}};
function getPending(month=monthNow()){return db.students.filter(s=>s.status!=='Inactive').map(s=>{const paid=db.fees.filter(f=>f.studentId===s.id&&f.month===month).reduce((a,f)=>a+Number(f.paid||0),0),fee=hallFee(s);return {...s,paid,balance:Math.max(0,fee-paid),fee}}).filter(x=>x.balance>0)}
function renderPending(){el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="pendingMonth" type="month" value="${monthNow()}"><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div id="pendingTable"></div></div>`;el('pendingMonth').onchange=drawPending;drawPending()}
function drawPending(){const month=el('pendingMonth')?.value||monthNow(),list=getPending(month);el('pendingTable').innerHTML=`<h3>Pending Fee List - ${esc(month)}</h3>${list.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Phone</th><th>Fee</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${money(x.fee)}</td><td>${money(x.paid)}</td><td><b>${money(x.balance)}</b></td><td><span class="badge pending">Pending</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No pending fees</div>'}`}
window.downloadPendingPDF=()=>{const month=el('pendingMonth')?.value||monthNow(),list=getPending(month),{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(`${db.settings.hallName} - Pending Fee List`,14,18);doc.setFontSize(10);let y=30;doc.text('Month: '+month,14,y);y+=10;list.forEach((x,i)=>{doc.text(`${i+1}. ${x.id} - ${x.name} | Phone: ${x.phone} | Balance: Rs.${x.balance}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save(`Pending-Fees-${month}.pdf`)};

function renderAttendance(){const d=today();el('pageContent').innerHTML=`<div class="card"><h3>Attendance - ${d}</h3><div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>${db.students.filter(s=>s.status!=='Inactive').map(s=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);return `<tr><td>${s.id}</td><td>${esc(s.name)}</td><td><span class="badge ${a?.status==='Present'?'present':a?.status==='Absent'?'absent':'pending'}">${a?.status||'Not Marked'}</span></td><td><button class="success" onclick="markAttendance('${s.id}','Present')">Present</button> <button class="danger" onclick="markAttendance('${s.id}','Absent')">Absent</button></td></tr>`}).join('')}</tbody></table></div></div>`}
window.markAttendance=(studentId,status)=>{db.attendance=db.attendance.filter(x=>!(x.studentId===studentId&&x.date===today()));db.attendance.push({studentId,date:today(),status,time:new Date().toLocaleTimeString()});logAction('attendance',`${studentName(studentId)} marked ${status}`);saveDB();renderAttendance()};
function renderMovement(){const outside=db.movements.filter(x=>x.status==='Outside');el('pageContent').innerHTML=`<div class="card"><h3>Student Going Out</h3><form id="moveForm" class="form-grid"><div class="field"><label>Student</label><select name="studentId">${studentOptions()}</select></div><div class="field"><label>Out Time</label><input type="datetime-local" name="outTime" value="${new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}"></div><div class="field"><label>Expected Return</label><input type="datetime-local" name="expectedReturn"></div><div class="field span-2"><label>Reason / Place</label><input name="reason" placeholder="Reason and place"></div><div class="field"><label>Google Maps Location Link</label><input name="location" placeholder="Paste Maps link"></div><div class="span-3"><button class="primary">Submit</button></div></form></div><div class="card"><h3>Currently Outside</h3>${outside.length?`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Out Time</th><th>Expected Return</th><th>Reason / Location</th><th>Status</th><th>Action</th></tr></thead><tbody>${outside.map(x=>`<tr><td>${esc(studentName(x.studentId))}</td><td>${esc(x.outTime)}</td><td>${esc(x.expectedReturn||'-')}</td><td>${esc(x.reason||'-')} ${x.location?`<a target="_blank" rel="noopener" href="${esc(x.location)}">Open Map</a>`:''}</td><td><span class="badge outside">Outside</span></td><td><button class="success" onclick="markReturned('${x.id}')">Returned</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students outside</div>'}</div>`;el('moveForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.status='Outside';o.returnTime='';db.movements.push(o);logAction('went_out',`${studentName(o.studentId)} went outside`);saveDB();renderMovement()}}
window.markReturned=id=>{const x=db.movements.find(m=>m.id===id);if(x){x.status='Returned';x.returnTime=new Date().toISOString().slice(0,16);logAction('returned',`${studentName(x.studentId)} returned`);saveDB();renderMovement()}};
function renderReports(){el('pageContent').innerHTML=`<div class="grid stats"><div class="card"><h3>Student List</h3><p class="muted">All student details.</p><button class="primary" onclick="downloadStudentsPDF()">Download PDF</button></div><div class="card"><h3>Pending Fees</h3><p class="muted">Current month pending list.</p><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div class="card"><h3>Backup</h3><p class="muted">Download complete data backup.</p><button class="secondary" onclick="downloadBackup()">Download JSON</button></div><div class="card"><h3>Restore Backup</h3><p class="muted">Restore previously downloaded JSON.</p><input id="restoreFile" type="file" accept="application/json"><button class="secondary" onclick="restoreBackup()">Restore</button></div></div>`}
window.downloadStudentsPDF=()=>{const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(`${db.settings.hallName} - Student List`,14,18);doc.setFontSize(10);let y=30;db.students.forEach((s,i)=>{doc.text(`${i+1}. ${s.id} - ${s.name} | ${s.phone} | Seat: ${s.seat||'-'} | ${s.course||'-'}`,14,y);y+=8;if(y>280){doc.addPage();y=20}});doc.save('Sri-Nidhi-Students.pdf')};
window.downloadBackup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='sri-nidhi-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.restoreBackup=()=>{const f=el('restoreFile').files[0];if(!f)return alert('Select backup file');const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.settings)throw Error();db=x;saveDB();alert('Backup restored');render('dashboard')}catch{alert('Invalid backup file')}};r.readAsText(f)};
function renderSettings(){el('pageContent').innerHTML=`<div class="card"><h3>Settings</h3><form id="settingsForm" class="form-grid"><div class="field"><label>Study Hall Name</label><input name="hallName" value="${esc(db.settings.hallName)}"></div><div class="field"><label>Default Monthly Fee</label><input type="number" name="monthlyFee" value="${db.settings.monthlyFee}"></div><div class="field"><label>Monthly Fee Due Day</label><input type="number" min="1" max="28" name="feeDueDay" value="${db.settings.feeDueDay||10}"></div><div class="field"><label>Admin Username</label><input name="adminUser" value="${esc(db.settings.adminUser)}"></div><div class="field"><label>Admin Password</label><input name="adminPass" value="${esc(db.settings.adminPass)}"></div><div class="span-3 actions"><button class="primary">Save Settings</button><button type="button" class="danger" onclick="resetDemo()">Reset Demo Data</button></div></form></div>`;el('settingsForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.monthlyFee=Number(o.monthlyFee);o.feeDueDay=Number(o.feeDueDay||10);db.settings=o;logAction('settings','Settings updated');saveDB();alert('Settings saved');render('dashboard')}}
window.resetDemo=()=>{if(confirm('Reset all data?')){db=clone(defaultDB);saveDB();render('dashboard')}};
window.render=render;

/* v1.3 stable feature layer */
db.notices=db.notices||[];db.diary=db.diary||[];saveDB();
function fmtDateTime(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('en-IN')}
function nextReceipt(){const nums=db.fees.map(f=>Number(String(f.receipt||'').replace(/\D/g,''))||0);return 'RC'+String(Math.max(0,...nums)+1).padStart(4,'0')}
function monthPaid(studentId,month){return db.fees.filter(f=>f.studentId===studentId&&f.month===month).reduce((a,f)=>a+Number(f.paid||0),0)}

window.viewStudent=function(id){const s=db.students.find(x=>x.id===id);if(!s)return;const fees=db.fees.filter(x=>x.studentId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const at=db.attendance.filter(x=>x.studentId===id).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const mv=db.movements.filter(x=>x.studentId===id).sort((a,b)=>String(b.outTime).localeCompare(String(a.outTime)));openModal(`<h2>Student Master File</h2><div class="profile-head">${s.photo?`<img class="profile-photo" src="${s.photo}" alt="">`:`<div class="profile-photo">${esc((s.name||'?')[0])}</div>`}<div><h2 style="margin:0">${esc(s.name)}</h2><div class="muted">${esc(s.id)} • ${esc(s.course||'-')} • Seat ${esc(s.seat||'-')}</div><div class="actions" style="margin-top:10px"><button class="primary" onclick="downloadStudentProfilePDF('${s.id}')">Profile PDF</button><button class="secondary" onclick="editStudent('${s.id}');closeModal()">Edit</button></div></div></div><div class="profile-grid">${[['Phone',s.phone],['Parent',s.parentName],['Parent Phone',s.parentPhone],['Emergency',s.emergencyPhone],['Gender',s.gender],['DOB',s.dob],['Batch',s.batch],['Join Date',s.joinDate],['Monthly Fee',money(hallFee(s))],['Status',s.status],['Address',s.address],['ID Proof',s.idProof]].map(x=>`<div class="profile-field"><small>${x[0]}</small><b>${esc(x[1]||'-')}</b></div>`).join('')}</div><div class="card"><h3>Fee History</h3>${fees.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Month</th><th>Paid</th><th>Date</th><th>Mode</th></tr></thead><tbody>${fees.map(f=>`<tr><td>${esc(f.receipt)}</td><td>${esc(f.month)}</td><td>${money(f.paid)}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No fee history</div>'}</div><div class="card"><h3>Attendance History</h3>${at.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Time</th></tr></thead><tbody>${at.slice(0,60).map(a=>`<tr><td>${esc(a.date)}</td><td>${esc(a.status)}</td><td>${esc(a.time||'-')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No attendance history</div>'}</div><div class="card"><h3>Entry / Exit History</h3>${mv.length?`<div class="table-wrap"><table><thead><tr><th>Out</th><th>Expected</th><th>Returned</th><th>Reason</th><th>Status</th></tr></thead><tbody>${mv.slice(0,40).map(m=>`<tr><td>${esc(fmtDateTime(m.outTime))}</td><td>${esc(fmtDateTime(m.expectedReturn))}</td><td>${esc(fmtDateTime(m.returnTime))}</td><td>${esc(m.reason||'-')}</td><td>${esc(m.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No movement history</div>'}</div>`)}
window.downloadStudentProfilePDF=function(id){const s=db.students.find(x=>x.id===id);if(!s)return;const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(17);doc.text(db.settings.hallName,14,18);doc.setFontSize(13);doc.text('Student Master Profile',14,27);doc.setFontSize(10);let y=40;const rows=[['Student ID',s.id],['Name',s.name],['Gender',s.gender],['Phone',s.phone],['Parent',s.parentName],['Parent Phone',s.parentPhone],['Emergency',s.emergencyPhone],['Course / Batch',`${s.course||'-'} / ${s.batch||'-'}`],['Seat',s.seat],['Join Date',s.joinDate],['Monthly Fee',`Rs.${hallFee(s)}`],['Status',s.status],['Address',s.address]];rows.forEach(r=>{doc.text(`${r[0]}: ${r[1]||'-'}`,14,y);y+=8});y+=4;doc.setFontSize(12);doc.text('Recent Fee History',14,y);y+=8;doc.setFontSize(9);db.fees.filter(f=>f.studentId===id).slice(-12).reverse().forEach(f=>{doc.text(`${f.receipt} | ${f.month} | Rs.${f.paid} | ${f.date} | ${f.mode}`,14,y);y+=7});doc.save(`${s.id}-${s.name}-Profile.pdf`)}

function renderFees(){const active=db.students.filter(s=>s.status!=='Inactive');el('pageContent').innerHTML=`<div class="card"><h3>Collect Monthly Fee</h3><form id="feeForm" class="form-grid"><div class="field"><label>Student</label><select id="feeStudent" name="studentId" required>${active.map(s=>`<option value="${s.id}">${esc(s.id)} - ${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Month</label><input id="feeMonth" type="month" name="month" value="${monthNow()}" required></div><div class="field"><label>Monthly Fee</label><input id="feeAmount" type="number" name="amount" readonly></div><div class="field"><label>Already Paid</label><input id="alreadyPaid" type="number" readonly></div><div class="field"><label>Balance</label><input id="feeBalance" type="number" readonly></div><div class="field"><label>Pay Now</label><input id="payNow" type="number" name="paid" required></div><div class="field"><label>Payment Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Payment Mode</label><select name="mode"><option>Cash</option><option>UPI</option><option>Bank</option></select></div><div class="field"><label>Transaction / Note</label><input name="reference" placeholder="Optional"></div><div class="span-3"><button class="primary">Save & Generate Receipt</button></div></form></div><div class="card"><h3>Payment History</h3><div id="feeTable"></div></div>`;const refresh=()=>{const sid=el('feeStudent').value,m=el('feeMonth').value,s=db.students.find(x=>x.id===sid),amount=hallFee(s),paid=monthPaid(sid,m),bal=Math.max(0,amount-paid);el('feeAmount').value=amount;el('alreadyPaid').value=paid;el('feeBalance').value=bal;el('payNow').value=bal||'';el('payNow').max=bal};el('feeStudent').onchange=refresh;el('feeMonth').onchange=refresh;refresh();el('feeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),balance=Number(el('feeBalance').value);o.id=uid();o.amount=Number(o.amount);o.paid=Number(o.paid);if(balance<=0)return alert('ఈ నెల fee ఇప్పటికే పూర్తిగా చెల్లించారు');if(o.paid<=0||o.paid>balance)return alert(`Pay Now amount ₹1 నుండి ${money(balance)} మధ్య ఉండాలి`);o.receipt=nextReceipt();db.fees.push(o);logAction('fee_paid',`Fee received: ${studentName(o.studentId)} - ${money(o.paid)} (${o.receipt})`);saveDB();downloadReceiptPDF(o.id);renderFees()};drawFees()}
function drawFees(){const list=[...db.fees].reverse();el('feeTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Student</th><th>Month</th><th>Paid</th><th>Date</th><th>Mode</th><th>Actions</th></tr></thead><tbody>${list.map(f=>`<tr><td>${esc(f.receipt||'-')}</td><td>${esc(studentName(f.studentId))}</td><td>${esc(f.month)}</td><td>${money(f.paid)}</td><td>${esc(f.date)}</td><td>${esc(f.mode)}</td><td class="receipt-actions"><button class="secondary" onclick="downloadReceiptPDF('${f.id}')">Receipt</button><button class="danger" onclick="deleteFee('${f.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No payments</div>'}
window.downloadReceiptPDF=function(id){const f=db.fees.find(x=>x.id===id),s=f&&db.students.find(x=>x.id===f.studentId);if(!f||!s)return;const {jsPDF}=window.jspdf,doc=new jsPDF({format:'a5'});doc.setFontSize(17);doc.text(db.settings.hallName,74,18,{align:'center'});doc.setFontSize(11);doc.text('FEE RECEIPT',74,27,{align:'center'});doc.line(12,32,136,32);doc.setFontSize(10);const rows=[['Receipt No',f.receipt],['Date',f.date],['Student ID',s.id],['Student Name',s.name],['Month',f.month],['Monthly Fee',`Rs.${f.amount}`],['Paid Now',`Rs.${f.paid}`],['Payment Mode',f.mode],['Reference',f.reference||'-'],['Total Paid for Month',`Rs.${monthPaid(s.id,f.month)}`],['Balance',`Rs.${Math.max(0,hallFee(s)-monthPaid(s.id,f.month))}`]];let y=43;rows.forEach(r=>{doc.text(r[0],16,y);doc.text(': '+String(r[1]),60,y);y+=9});doc.line(12,y+2,136,y+2);doc.text('Authorized Signature',92,y+18);doc.save(`${f.receipt}-${s.name}.pdf`)}

function renderAttendance(){const d=window._attendanceDate||today();el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="attendanceDate" type="date" value="${d}"><button class="success" onclick="markAllAttendance('Present')">Mark All Present</button><button class="danger" onclick="markAllAttendance('Absent')">Mark All Absent</button><button class="secondary" onclick="downloadAttendancePDF()">Day PDF</button></div><div id="attendanceTable"></div></div><div class="card"><h3>Monthly Attendance Summary</h3><div class="toolbar"><input id="attendanceMonth" type="month" value="${d.slice(0,7)}"><button class="primary" onclick="downloadMonthlyAttendancePDF()">Monthly PDF</button></div><div id="attendanceSummary"></div></div>`;el('attendanceDate').onchange=e=>{window._attendanceDate=e.target.value;renderAttendance()};el('attendanceMonth').onchange=drawAttendanceSummary;drawAttendanceDay();drawAttendanceSummary()}
function drawAttendanceDay(){const d=el('attendanceDate').value,students=db.students.filter(s=>s.status!=='Inactive');el('attendanceTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>${students.map(s=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);return `<tr><td>${s.id}</td><td>${esc(s.name)}</td><td><span class="badge ${a?.status==='Present'?'present':a?.status==='Absent'?'absent':'pending'}">${a?.status||'Not Marked'}</span></td><td><button class="success" onclick="markAttendanceForDate('${s.id}','Present','${d}')">Present</button> <button class="danger" onclick="markAttendanceForDate('${s.id}','Absent','${d}')">Absent</button></td></tr>`}).join('')}</tbody></table></div>`}
window.markAttendanceForDate=(studentId,status,date)=>{db.attendance=db.attendance.filter(x=>!(x.studentId===studentId&&x.date===date));db.attendance.push({studentId,date,status,time:new Date().toLocaleTimeString()});logAction('attendance',`${studentName(studentId)} marked ${status} on ${date}`);saveDB();drawAttendanceDay();drawAttendanceSummary()};window.markAllAttendance=status=>{const d=el('attendanceDate').value;db.students.filter(s=>s.status!=='Inactive').forEach(s=>{db.attendance=db.attendance.filter(x=>!(x.studentId===s.id&&x.date===d));db.attendance.push({studentId:s.id,date:d,status,time:new Date().toLocaleTimeString()})});logAction('attendance_bulk',`All students marked ${status} on ${d}`);saveDB();drawAttendanceDay();drawAttendanceSummary()}
function drawAttendanceSummary(){const m=el('attendanceMonth').value,list=db.students.filter(s=>s.status!=='Inactive').map(s=>{const a=db.attendance.filter(x=>x.studentId===s.id&&x.date.startsWith(m));return {s,p:a.filter(x=>x.status==='Present').length,a:a.filter(x=>x.status==='Absent').length}});el('attendanceSummary').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Present</th><th>Absent</th><th>Marked Days</th></tr></thead><tbody>${list.map(x=>`<tr><td>${x.s.id}</td><td>${esc(x.s.name)}</td><td>${x.p}</td><td>${x.a}</td><td>${x.p+x.a}</td></tr>`).join('')}</tbody></table></div>`}
window.downloadAttendancePDF=()=>{const d=el('attendanceDate').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(15);doc.text(`${db.settings.hallName} - Attendance`,14,18);doc.setFontSize(10);doc.text(`Date: ${d}`,14,27);let y=38;db.students.filter(s=>s.status!=='Inactive').forEach((s,i)=>{const a=db.attendance.find(x=>x.studentId===s.id&&x.date===d);doc.text(`${i+1}. ${s.id} - ${s.name} - ${a?.status||'Not Marked'}`,14,y);y+=7;if(y>282){doc.addPage();y=18}});doc.save(`Attendance-${d}.pdf`)}
window.downloadMonthlyAttendancePDF=()=>{const m=el('attendanceMonth').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(15);doc.text(`${db.settings.hallName} - Monthly Attendance`,14,18);doc.setFontSize(10);doc.text(`Month: ${m}`,14,27);let y=38;db.students.filter(s=>s.status!=='Inactive').forEach((s,i)=>{const a=db.attendance.filter(x=>x.studentId===s.id&&x.date.startsWith(m)),p=a.filter(x=>x.status==='Present').length,ab=a.filter(x=>x.status==='Absent').length;doc.text(`${i+1}. ${s.id} - ${s.name} | Present: ${p} | Absent: ${ab}`,14,y);y+=7;if(y>282){doc.addPage();y=18}});doc.save(`Monthly-Attendance-${m}.pdf`)}

function renderNotices(){const list=[...(db.notices||[])].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));el('pageContent').innerHTML=`<div class="card"><h3>Add Notice</h3><form id="noticeForm" class="form-grid"><div class="field span-2"><label>Title</label><input name="title" required></div><div class="field"><label>Priority</label><select name="priority"><option>Normal</option><option>Urgent</option></select></div><div class="field span-3"><label>Notice</label><textarea name="message" required></textarea></div><div class="span-3"><button class="primary">Publish Notice</button></div></form></div><div class="card"><h3>Notice Board</h3>${list.length?list.map(n=>`<div class="notice-card ${n.priority==='Urgent'?'urgent':''}"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(n.title)}</b><button class="danger" onclick="deleteNotice('${n.id}')">Delete</button></div><p>${esc(n.message)}</p><small class="muted">${fmtDateTime(n.createdAt)} • ${esc(n.priority)}</small></div>`).join(''):'<div class="empty">No notices</div>'}</div>`;el('noticeForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=uid();o.createdAt=new Date().toISOString();db.notices.push(o);logAction('notice',`Notice published: ${o.title}`);saveDB();renderNotices()}}
window.deleteNotice=id=>{if(confirm('Delete notice?')){db.notices=db.notices.filter(x=>x.id!==id);saveDB();renderNotices()}}
function renderDiary(){const d=window._diaryDate||today(),entry=db.diary.find(x=>x.date===d)||{};el('pageContent').innerHTML=`<div class="card"><div class="toolbar"><input id="diaryDate" type="date" value="${d}"><button class="secondary" onclick="downloadDailyClosingPDF()">Closing Report PDF</button></div><form id="diaryForm" class="form-grid"><div class="field span-3"><label>Important Notes</label><textarea name="notes" placeholder="Admissions, visitors, complaints, special events...">${esc(entry.notes||'')}</textarea></div><div class="field"><label>Cash Expenses</label><input type="number" name="expenses" value="${Number(entry.expenses||0)}"></div><div class="field span-2"><label>Expense Details</label><input name="expenseDetails" value="${esc(entry.expenseDetails||'')}"></div><div class="span-3"><button class="primary">Save Daily Diary</button></div></form></div><div class="card"><h3>Automatic Day Summary</h3><div id="dailySummary" class="diary-summary"></div></div>`;el('diaryDate').onchange=e=>{window._diaryDate=e.target.value;renderDiary()};el('diaryForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.date=d;o.expenses=Number(o.expenses||0);o.updatedAt=new Date().toISOString();db.diary=db.diary.filter(x=>x.date!==d);db.diary.push(o);logAction('diary',`Daily diary saved for ${d}`);saveDB();renderDiary()};el('dailySummary').textContent=buildDailySummary(d)}
function buildDailySummary(d){const admissions=db.students.filter(s=>s.joinDate===d).length,fees=db.fees.filter(f=>f.date===d),collection=fees.reduce((a,f)=>a+Number(f.paid||0),0),present=db.attendance.filter(a=>a.date===d&&a.status==='Present').length,absent=db.attendance.filter(a=>a.date===d&&a.status==='Absent').length,out=db.movements.filter(m=>String(m.outTime||'').startsWith(d)).length,returned=db.movements.filter(m=>String(m.returnTime||'').startsWith(d)).length,entry=db.diary.find(x=>x.date===d)||{};return `Date: ${d}\nNew Admissions: ${admissions}\nFee Transactions: ${fees.length}\nFee Collection: ${money(collection)}\nPresent: ${present}\nAbsent: ${absent}\nWent Outside: ${out}\nReturned: ${returned}\nExpenses: ${money(entry.expenses||0)}\nNet Cash Position: ${money(collection-Number(entry.expenses||0))}\n\nNotes: ${entry.notes||'-'}\nExpense Details: ${entry.expenseDetails||'-'}`}
window.downloadDailyClosingPDF=()=>{const d=el('diaryDate').value,{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text(db.settings.hallName,14,18);doc.setFontSize(12);doc.text('Daily Closing Report',14,27);doc.setFontSize(10);const lines=doc.splitTextToSize(buildDailySummary(d),180);doc.text(lines,14,40);doc.save(`Daily-Closing-${d}.pdf`)}

function renderReports(){el('pageContent').innerHTML=`<div class="grid stats"><div class="card"><h3>Student List</h3><p class="muted">All active and inactive students.</p><button class="primary" onclick="downloadStudentsPDF()">Download PDF</button></div><div class="card"><h3>Pending Fees</h3><p class="muted">Current month pending list.</p><button class="primary" onclick="downloadPendingPDF()">Download PDF</button></div><div class="card"><h3>Daily Closing</h3><p class="muted">Today collection, attendance and movement.</p><button class="primary" onclick="render('diary')">Open Diary</button></div><div class="card"><h3>Backup</h3><p class="muted">Complete local database backup.</p><button class="secondary" onclick="downloadBackup()">Download JSON</button></div><div class="card"><h3>Restore Backup</h3><p class="muted">Restore a valid Sri Nidhi backup.</p><input id="restoreFile" type="file" accept="application/json"><button class="secondary" onclick="restoreBackup()">Restore</button></div><div class="card"><h3>Install as App</h3><p class="muted">Chrome menu → Add to Home screen.</p><div class="install-tip">Works after GitHub Pages deployment.</div></div></div>`}

/* v2.5 Build 2 — Student Master, PDF/Excel/CSV bulk import */
let studentImportRows=[];
function uniqueStudentValues(key){return [...new Set(db.students.map(s=>String(s[key]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function renderStudents(){const batches=uniqueStudentValues('batch');el('pageContent').innerHTML=`
<div class="student-summary-grid">
 <div><b>${db.students.length}</b><span>Total Students</span></div>
 <div><b>${db.students.filter(s=>(s.status||'Active')==='Active').length}</b><span>Active</span></div>
 <div><b>${db.students.filter(s=>(s.status||'Active')==='Inactive').length}</b><span>Inactive</span></div>
 <div><b>${uniqueStudentValues('batch').length}</b><span>Batches</span></div>
</div>
<div class="student-actions-grid">
 <button class="student-action-card" onclick="showStudentForm()"><b>Add Single Student</b><span>Enter one student manually</span></button>
 <button class="student-action-card" onclick="openStudentImport('pdf')"><b>Import PDF</b><span>Auto read, preview and bulk save</span></button>
 <button class="student-action-card" onclick="openStudentPaste()"><b>Paste Data Bulk Add</b><span>Paste rows, parse, preview and save</span></button>
 <button class="student-action-card" onclick="openStudentImport('sheet')"><b>Excel / CSV Import</b><span>Upload spreadsheet or CSV file</span></button>
</div>
<div class="card student-master-card">
 <div class="student-toolbar">
  <input id="studentSearch" placeholder="Search name, ID, phone, parent, course, batch, seat or Aadhaar">
  <select id="batchFilter"><option value="">All Batches</option>${batches.map(x=>`<option>${esc(x)}</option>`).join('')}</select>
  <select id="statusFilter"><option value="">All Status</option><option>Active</option><option>Inactive</option></select>
  <select id="genderFilter"><option value="">All Gender</option><option>Female</option><option>Male</option><option>Other</option></select>
  <button class="secondary" onclick="clearStudentFilters()">Clear</button>
 </div>
 <div id="studentResultInfo" class="student-result-info"></div>
 <div id="studentsTable"></div>
</div>`;
['studentSearch','batchFilter','statusFilter','genderFilter'].forEach(id=>{const x=el(id);if(x)x[id==='studentSearch'?'oninput':'onchange']=drawStudents});drawStudents()}
window.clearStudentFilters=function(){['studentSearch','batchFilter','statusFilter','genderFilter'].forEach(id=>{if(el(id))el(id).value=''});drawStudents()}
function studentCard(s){return `<article class="student-mobile-card">
 <div class="student-card-head" onclick="viewStudent('${s.id}')">${avatar(s)}<div><h3>${esc(s.name)}</h3><p>${esc(s.id)} · ${esc(s.course||'No Course')}</p></div><span class="badge ${(s.status||'Active')==='Inactive'?'absent':'present'}">${esc(s.status||'Active')}</span></div>
 <div class="student-card-details"><span><b>Phone</b>${esc(s.phone||'-')}</span><span><b>Batch</b>${esc(s.batch||'-')}</span><span><b>Seat</b>${esc(s.seat||'-')}</span><span><b>Fee</b>${money(hallFee(s))}</span></div>
 <div class="student-card-parent"><b>Parent:</b> ${esc(s.parentName||s.fatherName||s.motherName||'-')} ${s.parentPhone||s.fatherPhone?`· ${esc(s.parentPhone||s.fatherPhone)}`:''}</div>
 <div class="student-card-actions"><button class="secondary" onclick="viewStudent('${s.id}')">View</button><button class="secondary" onclick="editStudent('${s.id}')">Edit</button><button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></div>
 </article>`}
function drawStudents(){const q=(el('studentSearch')?.value||'').trim().toLowerCase(),g=el('genderFilter')?.value||'',st=el('statusFilter')?.value||'',batch=el('batchFilter')?.value||'';const list=db.students.filter(s=>(!g||s.gender===g)&&(!st||(s.status||'Active')===st)&&(!batch||(s.batch||'')===batch)&&[s.id,s.name,s.phone,s.parentName,s.parentPhone,s.fatherName,s.fatherPhone,s.motherName,s.motherPhone,s.course,s.batch,s.seat,s.aadhaar,s.address].join(' ').toLowerCase().includes(q));const info=el('studentResultInfo');if(info)info.textContent=`Showing ${list.length} of ${db.students.length} students`;el('studentsTable').innerHTML=list.length?`<div class="student-mobile-list">${list.map(studentCard).join('')}</div><div class="student-desktop-table table-wrap"><table><thead><tr><th>Student</th><th>ID</th><th>Phone</th><th>Parent</th><th>Course / Batch</th><th>Joining</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td><div class="student-name">${avatar(s)}<div><b>${esc(s.name)}</b><small>${esc(s.seat||'No seat')}</small></div></div></td><td>${esc(s.id)}</td><td>${esc(s.phone||'-')}</td><td>${esc(s.parentName||s.fatherName||s.motherName||'-')}<br><small>${esc(s.parentPhone||s.fatherPhone||'-')}</small></td><td>${esc(s.course||'-')} / ${esc(s.batch||'-')}</td><td>${esc(s.joinDate||'-')}</td><td>${money(hallFee(s))}</td><td><span class="badge ${(s.status||'Active')==='Inactive'?'absent':'present'}">${esc(s.status||'Active')}</span></td><td><div class="row-actions"><button class="secondary" onclick="viewStudent('${s.id}')">View</button><button class="secondary" onclick="editStudent('${s.id}')">Edit</button><button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No students match the selected search or filters.</div>'}
function studentForm(s={}){return `<form id="studentForm" class="form-grid">
<div class="section-title">Student Details</div>
<div class="field"><label>Student ID *</label><input name="id" value="${esc(s.id||nextStudentId())}" required ${s.id?'readonly':''}></div><div class="field"><label>Full Name *</label><input name="name" value="${esc(s.name||'')}" required></div><div class="field"><label>Gender</label><select name="gender"><option ${s.gender==='Female'?'selected':''}>Female</option><option ${s.gender==='Male'?'selected':''}>Male</option><option ${s.gender==='Other'?'selected':''}>Other</option></select></div>
<div class="field"><label>Date of Birth</label><input type="date" name="dob" value="${esc(s.dob||'')}"></div><div class="field"><label>Student Phone</label><input name="phone" inputmode="numeric" value="${esc(s.phone||'')}"></div><div class="field"><label>Student Aadhaar</label><input name="aadhaar" inputmode="numeric" maxlength="12" value="${esc(s.aadhaar||'')}"></div>
<div class="field"><label>Photo</label><input id="photoInput" type="file" accept="image/*"></div><div class="field"><label>Photo Preview</label><img id="photoPreview" class="photo-preview" src="${s.photo||''}" alt=""></div>
<div class="section-title">Parent Details</div>
<div class="field"><label>Father Name</label><input name="fatherName" value="${esc(s.fatherName||s.parentName||'')}"></div><div class="field"><label>Father Phone</label><input name="fatherPhone" inputmode="numeric" value="${esc(s.fatherPhone||s.parentPhone||'')}"></div><div class="field"><label>Father Aadhaar</label><input name="fatherAadhaar" inputmode="numeric" maxlength="12" value="${esc(s.fatherAadhaar||'')}"></div>
<div class="field"><label>Mother Name</label><input name="motherName" value="${esc(s.motherName||'')}"></div><div class="field"><label>Mother Phone</label><input name="motherPhone" inputmode="numeric" value="${esc(s.motherPhone||'')}"></div><div class="field"><label>Mother Aadhaar</label><input name="motherAadhaar" inputmode="numeric" maxlength="12" value="${esc(s.motherAadhaar||'')}"></div>
<div class="field"><label>Emergency Phone</label><input name="emergencyPhone" inputmode="numeric" value="${esc(s.emergencyPhone||'')}"></div><div class="field span-3"><label>Address</label><textarea name="address">${esc(s.address||'')}</textarea></div>
<div class="section-title">Study Hall & Fee Details</div>
<div class="field"><label>Course / Exam</label><input name="course" value="${esc(s.course||'')}"></div><div class="field"><label>Batch / Timing</label><input name="batch" value="${esc(s.batch||'')}"></div><div class="field"><label>Seat Number</label><input name="seat" value="${esc(s.seat||'')}"></div>
<div class="field"><label>Joining Date</label><input type="date" name="joinDate" value="${esc(s.joinDate||today())}"></div><div class="field"><label>Monthly Fee</label><input type="number" name="monthlyFee" value="${hallFee(s)}"></div><div class="field"><label>Next Due Date</label><input type="date" name="nextDueDate" value="${esc(s.nextDueDate||addOneMonth(s.joinDate||today()))}"></div>
<div class="field"><label>Status</label><select name="status"><option ${s.status!=='Inactive'?'selected':''}>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></div><input type="hidden" name="photo" value="${s.photo||''}"><input type="hidden" name="parentName" value="${esc(s.parentName||'')}"><input type="hidden" name="parentPhone" value="${esc(s.parentPhone||'')}">
<div class="span-3 actions"><button class="primary" type="submit">Save Student</button><button type="button" class="secondary" onclick="closeModal()">Cancel</button></div></form>`}
function addOneMonth(d){const x=new Date((d||today())+'T00:00:00');x.setMonth(x.getMonth()+1);return x.toISOString().slice(0,10)}
function bindStudentForm(editId=null){const form=el('studentForm'),photo=el('photoInput'),preview=el('photoPreview');if(photo)photo.onchange=()=>{const file=photo.files[0];if(!file)return;if(file.size>800000)return alert('Photo size 800 KB లోపు ఉండాలి.');const r=new FileReader();r.onload=()=>{form.elements.photo.value=r.result;preview.src=r.result};r.readAsDataURL(file)};form.elements.joinDate.onchange=()=>{if(!editId)form.elements.nextDueDate.value=addOneMonth(form.elements.joinDate.value)};form.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(form));o.monthlyFee=Number(o.monthlyFee||db.settings.monthlyFee);o.parentName=o.fatherName||o.motherName||'';o.parentPhone=o.fatherPhone||o.motherPhone||'';for(const k of ['phone','fatherPhone','motherPhone','emergencyPhone']){const v=(o[k]||'').replace(/\D/g,'');if(v&&v.length!==10)return alert(`${k} number 10 digits ఉండాలి`);o[k]=v}for(const k of ['aadhaar','fatherAadhaar','motherAadhaar']){const v=(o[k]||'').replace(/\D/g,'');if(v&&v.length!==12)return alert(`${k} 12 digits ఉండాలి`);o[k]=v}const duplicate=db.students.find(s=>s.id!==editId&&((o.aadhaar&&s.aadhaar===o.aadhaar)||(o.phone&&s.phone===o.phone)));if(duplicate)return alert(`Duplicate warning: ${duplicate.id} - ${duplicate.name}`);if(editId)db.students=db.students.map(s=>s.id===editId?o:s);else{if(db.students.some(s=>s.id===o.id))return alert('Student ID already exists');db.students.push(o)}saveDB();closeModal();render('students');alert('Student saved successfully')}}
window.showStudentForm=()=>{openModal(`<h3>Add Single Student</h3>${studentForm()}`);bindStudentForm()};
window.editStudent=id=>{const s=db.students.find(x=>x.id===id);openModal(`<h3>Edit Student</h3>${studentForm(s)}`);bindStudentForm(id)};
window.openStudentPaste=function(){studentImportRows=[];openModal(`<h2>Paste Data Bulk Add</h2><p class="muted">Excel, WhatsApp, Google Keep లేదా table నుంచి student data paste చేయండి. మొదటి row headings ఉంటే వాటిని automaticగా గుర్తిస్తుంది.</p><div class="paste-help"><b>Recommended columns:</b> Student ID, Student Name, Gender, DOB, Student Phone, Student Aadhaar, Father Name, Father Phone, Mother Name, Mother Phone, Address, Course, Batch, Seat, Joining Date, Monthly Fee, Status</div><textarea id="studentPasteData" class="student-paste-box" placeholder="Student ID\tStudent Name\tPhone\tFather Name\nSN0001\tRavi Kumar\t9876543210\tRamesh"></textarea><div class="actions paste-actions"><button class="primary" onclick="parseStudentPaste()">Parse Data</button><button class="secondary" onclick="loadPasteSample()">Show & Parse Sample</button><button class="secondary" onclick="clearStudentPaste()">Clear</button></div><div id="importMessage" class="import-message">Data paste చేసి <b>Parse Data</b> నొక్కండి.</div><div id="studentImportPreview"></div>`);const t=el('studentPasteData');if(t)t.addEventListener('paste',()=>setTimeout(()=>{if(t.value.trim())parseStudentPaste()},120))};
window.loadPasteSample=function(){const t=el('studentPasteData');if(t){t.value='Student ID\tStudent Name\tGender\tStudent Phone\tFather Name\tMother Name\tCourse\tBatch\tJoining Date\tMonthly Fee\nSN0001\tSample Student\tFemale\t9876543210\tFather Name\tMother Name\tDSC\tMorning\t2026-07-20\t1500';parseStudentPaste()}};
window.clearStudentPaste=function(){const t=el('studentPasteData');if(t)t.value='';studentImportRows=[];const p=el('studentImportPreview');if(p)p.innerHTML='';const m=el('importMessage');if(m)m.textContent=''};
window.parseStudentPaste=function(){const text=(el('studentPasteData')?.value||'').trim();if(!text)return alert('Student data paste చేయండి');try{const raw=parsePastedStudentData(text);studentImportRows=raw.map(normalizeImportStudent);renderStudentImportPreview();setTimeout(()=>el('studentImportPreview')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}catch(e){console.error(e);el('importMessage').textContent='Data parse కాలేదు: '+e.message}};
function parsePastedStudentData(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return[];const splitLine=line=>{if(line.includes('\t'))return line.split('\t').map(x=>x.trim());if(line.includes('|'))return line.split(/\s*\|\s*/).map(x=>x.trim());if(line.includes(','))return parseCSV(line+'\n').length?[]:splitCSVLine(line);return line.split(/\s{2,}/).map(x=>x.trim()).filter(Boolean)};const splitCSVLine=line=>{const out=[];let q=false,v='';for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out};let rows=lines.map(line=>line.includes(',')?splitCSVLine(line):splitLine(line));const looksHeader=rows[0].some(v=>/(student|name|phone|mobile|aadhaar|father|mother|gender|course|batch|joining|fee|status|address|seat|dob|id)/i.test(v));let headers;if(looksHeader){headers=rows.shift()}else{headers=['Student ID','Student Name','Gender','Student Phone','Student Aadhaar','Father Name','Father Phone','Mother Name','Mother Phone','Address','Course','Batch','Seat','Joining Date','Monthly Fee','Status']}
return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
window.openStudentImport=function(type){const accept=type==='pdf'?'.pdf':'.xlsx,.xls,.csv';openModal(`<h2>${type==='pdf'?'PDF Auto Import':'Excel / CSV Bulk Add'}</h2><p class="muted">File select చేసిన తర్వాత data previewలో చూపబడుతుంది. Save ముందు ప్రతి row edit చేయవచ్చు.</p><div class="import-drop"><input id="studentImportFile" type="file" accept="${accept}"><button class="primary" onclick="readStudentImport('${type}')">Read File</button></div><div id="importMessage" class="import-message"></div><div id="studentImportPreview"></div>`) };
window.readStudentImport=async function(type){const f=el('studentImportFile')?.files?.[0];if(!f)return alert('ముందుగా file select చేయండి');el('importMessage').textContent='Reading file...';try{studentImportRows=type==='pdf'?await readStudentPDF(f):await readStudentSheet(f);studentImportRows=studentImportRows.map(normalizeImportStudent).filter(x=>x.name);renderStudentImportPreview()}catch(e){console.error(e);el('importMessage').textContent='File read కాలేదు: '+e.message}}
async function readStudentSheet(file){if(file.name.toLowerCase().endsWith('.csv'))return parseCSV(await file.text());if(!window.XLSX)throw new Error('Excel reader load కాలేదు. Internet connection check చేయండి.');const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{defval:''})}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const split=line=>{const out=[];let q=false,v='';for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v.trim());v=''}else v+=c}out.push(v.trim());return out};const h=split(lines[0]);return lines.slice(1).map(l=>Object.fromEntries(split(l).map((v,i)=>[h[i]||`Column${i+1}`,v])))}
async function readStudentPDF(file){if(!window.pdfjsLib)throw new Error('PDF reader load కాలేదు. Internet connection check చేయండి.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let lines=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),items=content.items.map(i=>({s:i.str.trim(),x:i.transform[4],y:i.transform[5]})).filter(i=>i.s);const groups={};items.forEach(i=>{const y=Math.round(i.y/3)*3;(groups[y]??=[]).push(i)});Object.keys(groups).sort((a,b)=>b-a).forEach(y=>lines.push(groups[y].sort((a,b)=>a.x-b.x).map(i=>i.s).join(' | ')))}return parsePDFStudentLines(lines)}
function parsePDFStudentLines(lines){const useful=lines.filter(x=>/\d/.test(x)&&x.length>3);let rows=[];for(const line of useful){const c=line.split(/\s*\|\s*|\t|\s{2,}/).map(x=>x.trim()).filter(Boolean);if(c.length<2)continue;const phone=c.find(x=>/^\d{10}$/.test(x.replace(/\D/g,'')));const aadhaar=c.find(x=>/^\d{12}$/.test(x.replace(/\D/g,'')));const id=c.find(x=>/^(SN|STU|STD)?\d{2,}$/i.test(x.replace(/[-/ ]/g,'')));const name=c.find(x=>/[A-Za-z\u0C00-\u0C7F]{3}/.test(x)&&!/(father|mother|phone|aadhaar|name|student|class|batch)/i.test(x));if(name)rows.push({id:id||'',name,phone:phone||'',aadhaar:aadhaar||'',fatherName:c[c.indexOf(name)+1]||'',raw:line})}return rows}
function normalizeImportStudent(r){const pick=(...names)=>{for(const [k,v] of Object.entries(r)){const key=k.toLowerCase().replace(/[^a-z0-9]/g,'');if(names.some(n=>key===n||key.includes(n)))return String(v||'').trim()}return''};return {id:pick('studentid','id','admissionno','rollno')||'',name:pick('studentname','fullname','name'),gender:pick('gender','sex')||'Female',dob:dateVal(pick('dob','dateofbirth')),phone:digits(pick('studentphone','mobile','phone'),10),aadhaar:digits(pick('studentaadhaar','aadhaar'),12),fatherName:pick('fathername','father','parentname','guardian'),fatherPhone:digits(pick('fatherphone','parentphone','guardianphone'),10),fatherAadhaar:digits(pick('fatheraardhaar'),12),motherName:pick('mothername','mother'),motherPhone:digits(pick('motherphone'),10),motherAadhaar:digits(pick('motheraadhaar'),12),address:pick('address'),course:pick('course','exam','class'),batch:pick('batch','timing'),seat:pick('seat','seatno'),joinDate:dateVal(pick('joiningdate','joindate','admissiondate'))||today(),monthlyFee:Number(pick('monthlyfee','fee','amount')||db.settings.monthlyFee),status:pick('status')||'Active'}}
function digits(v,n){const d=String(v||'').replace(/\D/g,'');return d.length===n?d:''}function dateVal(v){if(!v)return'';const d=new Date(v);return isNaN(d)?'':d.toISOString().slice(0,10)}
function renderStudentImportPreview(){const msg=el('importMessage');msg.textContent=studentImportRows.length?`${studentImportRows.length} records found. Check and save.`:'Student records గుర్తించబడలేదు. Excel/CSV template ఉపయోగించండి లేదా PDFలో table text ఉండాలి.';const box=el('studentImportPreview');if(!studentImportRows.length){box.innerHTML='<button class="secondary" onclick="downloadStudentTemplate()">Download CSV Template</button>';return}box.innerHTML=`<div class="import-summary"><b>${studentImportRows.length} Records</b><span id="importValidCount"></span></div><div class="table-wrap import-table"><table><thead><tr><th>#</th><th>ID</th><th>Name *</th><th>Phone</th><th>Father</th><th>Mother</th><th>Join Date</th><th>Fee</th><th></th></tr></thead><tbody>${studentImportRows.map((r,i)=>`<tr data-i="${i}"><td>${i+1}</td><td><input data-k="id" value="${esc(r.id)}" placeholder="Auto"></td><td><input data-k="name" value="${esc(r.name)}"></td><td><input data-k="phone" value="${esc(r.phone)}"></td><td><input data-k="fatherName" value="${esc(r.fatherName)}"></td><td><input data-k="motherName" value="${esc(r.motherName)}"></td><td><input type="date" data-k="joinDate" value="${esc(r.joinDate)}"></td><td><input type="number" data-k="monthlyFee" value="${r.monthlyFee}"></td><td><button class="danger" onclick="removeImportRow(${i})">×</button></td></tr>`).join('')}</tbody></table></div><div class="actions"><button class="primary" onclick="saveImportedStudents()">Save All Students</button><button class="secondary" onclick="downloadStudentTemplate()">CSV Template</button></div>`}
window.removeImportRow=i=>{studentImportRows.splice(i,1);renderStudentImportPreview()};
window.saveImportedStudents=function(){document.querySelectorAll('#studentImportPreview tbody tr').forEach(tr=>{const i=Number(tr.dataset.i);tr.querySelectorAll('[data-k]').forEach(inp=>studentImportRows[i][inp.dataset.k]=inp.type==='number'?Number(inp.value):inp.value.trim())});let added=0,skipped=[];for(const r of studentImportRows){if(!r.name){skipped.push('Missing name');continue}r.id=r.id||nextStudentId();const dup=db.students.find(s=>s.id===r.id||(r.aadhaar&&s.aadhaar===r.aadhaar)||(r.phone&&s.phone===r.phone));if(dup){skipped.push(`${r.name} (${dup.id})`);continue}r.nextDueDate=addOneMonth(r.joinDate);r.parentName=r.fatherName||r.motherName||'';r.parentPhone=r.fatherPhone||r.motherPhone||'';db.students.push(r);added++}db.importHistory=db.importHistory||[];db.importHistory.push({id:uid(),date:new Date().toISOString(),added,skipped:skipped.length});saveDB();closeModal();render('students');alert(`${added} students added. ${skipped.length} duplicates/invalid skipped.`)}
window.downloadStudentTemplate=function(){const csv='Student ID,Student Name,Gender,DOB,Student Phone,Student Aadhaar,Father Name,Father Phone,Father Aadhaar,Mother Name,Mother Phone,Mother Aadhaar,Address,Course,Batch,Seat,Joining Date,Monthly Fee,Status\nSN0001,Sample Student,Female,2010-01-01,9876543210,123456789012,Father Name,9876543211,123456789013,Mother Name,9876543212,123456789014,Address,DSC,Morning,A01,2026-07-20,1500,Active';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Sri-Nidhi-Student-Import-Template.csv';a.click();URL.revokeObjectURL(a.href)}

/* v2.5 Build 5 — mobile-first preview grid, row actions and save workflow */
function syncStudentImportRows(){
 document.querySelectorAll('#studentImportPreview tbody tr[data-i]').forEach(tr=>{
  const i=Number(tr.dataset.i),row=studentImportRows[i]; if(!row)return;
  tr.querySelectorAll('[data-k]').forEach(inp=>row[inp.dataset.k]=inp.type==='number'?Number(inp.value||0):inp.value.trim());
  const cb=tr.querySelector('.import-select'); if(cb)row._selected=cb.checked;
 });
}
function importRowIssues(row,index){
 const issues=[];
 if(!String(row.name||'').trim())issues.push('Student Name required');
 const id=String(row.id||'').trim(),phone=String(row.phone||'').replace(/\D/g,''),aadhaar=String(row.aadhaar||'').replace(/\D/g,'');
 if(phone&&phone.length!==10)issues.push('Phone must be 10 digits');
 if(aadhaar&&aadhaar.length!==12)issues.push('Aadhaar must be 12 digits');
 const otherRows=studentImportRows.filter((_,i)=>i!==index);
 if(id&&(db.students.some(s=>s.id===id)||otherRows.some(r=>String(r.id||'').trim()===id)))issues.push('Duplicate Student ID');
 if(phone&&(db.students.some(s=>s.phone===phone)||otherRows.some(r=>String(r.phone||'').replace(/\D/g,'')===phone)))issues.push('Duplicate Phone');
 if(aadhaar&&(db.students.some(s=>s.aadhaar===aadhaar)||otherRows.some(r=>String(r.aadhaar||'').replace(/\D/g,'')===aadhaar)))issues.push('Duplicate Aadhaar');
 return issues;
}
function updateStudentImportValidation(){
 syncStudentImportRows();
 let valid=0,duplicate=0,invalid=0,selected=0;
 studentImportRows.forEach((r,i)=>{
  const issues=importRowIssues(r,i),tr=document.querySelector(`#studentImportPreview tr[data-i="${i}"]`);
  r._issues=issues;
  if(r._selected!==false)selected++;
  if(!issues.length)valid++; else if(issues.some(x=>x.startsWith('Duplicate')))duplicate++; else invalid++;
  if(tr){tr.classList.toggle('row-valid',!issues.length);tr.classList.toggle('row-invalid',issues.length>0);tr.classList.toggle('row-duplicate',issues.some(x=>x.startsWith('Duplicate')));const cell=tr.querySelector('.import-status-cell');if(cell)cell.innerHTML=issues.length?`<span class="import-error" title="${esc(issues.join(', '))}">${esc(issues[0])}</span>`:'<span class="import-ok">Valid</span>';}
 });
 const s=el('importStats');if(s)s.innerHTML=`<span><b>${studentImportRows.length}</b> Parsed</span><span><b>${valid}</b> Valid</span><span><b>${duplicate}</b> Duplicate</span><span><b>${invalid}</b> Invalid</span><span><b>${selected}</b> Selected</span>`;
 const all=el('importSelectAll');if(all)all.checked=studentImportRows.length>0&&studentImportRows.every(r=>r._selected!==false);
}
window.toggleImportAll=function(checked){studentImportRows.forEach(r=>r._selected=checked);document.querySelectorAll('.import-select').forEach(x=>x.checked=checked);updateStudentImportValidation()};
window.toggleImportRow=function(i,checked){if(studentImportRows[i])studentImportRows[i]._selected=checked;updateStudentImportValidation()};
window.renderStudentImportPreview=function(){
 const msg=el('importMessage');
 msg.textContent=studentImportRows.length?`${studentImportRows.length} records parsed. Invalid or duplicate rows are highlighted.`:'Student records గుర్తించబడలేదు. Excel/CSV template ఉపయోగించండి లేదా PDFలో table text ఉండాలి.';
 const box=el('studentImportPreview');if(!box)return;
 if(!studentImportRows.length){box.innerHTML='<button class="secondary" onclick="downloadStudentTemplate()">Download CSV Template</button>';return}
 studentImportRows.forEach(r=>{if(r._selected===undefined)r._selected=true});
 box.innerHTML=`<div id="importStats" class="import-stats"></div><div class="table-wrap import-table excel-preview"><table><thead><tr><th><input id="importSelectAll" type="checkbox" checked onchange="toggleImportAll(this.checked)"></th><th>#</th><th>ID</th><th>Name *</th><th>Phone</th><th>Aadhaar</th><th>Father</th><th>Mother</th><th>Course</th><th>Batch</th><th>Join Date</th><th>Fee</th><th>Validation</th><th></th></tr></thead><tbody>${studentImportRows.map((r,i)=>`<tr data-i="${i}"><td><input class="import-select" type="checkbox" ${r._selected!==false?'checked':''} onchange="toggleImportRow(${i},this.checked)"></td><td>${i+1}</td><td><input data-k="id" value="${esc(r.id)}" placeholder="Auto"></td><td><input data-k="name" value="${esc(r.name)}"></td><td><input data-k="phone" inputmode="numeric" value="${esc(r.phone)}"></td><td><input data-k="aadhaar" inputmode="numeric" value="${esc(r.aadhaar)}"></td><td><input data-k="fatherName" value="${esc(r.fatherName)}"></td><td><input data-k="motherName" value="${esc(r.motherName)}"></td><td><input data-k="course" value="${esc(r.course)}"></td><td><input data-k="batch" value="${esc(r.batch)}"></td><td><input type="date" data-k="joinDate" value="${esc(r.joinDate)}"></td><td><input type="number" data-k="monthlyFee" value="${Number(r.monthlyFee||0)}"></td><td class="import-status-cell"></td><td><button class="danger mini" onclick="removeImportRow(${i})">×</button></td></tr>`).join('')}</tbody></table></div><div class="actions import-actions"><button class="secondary" onclick="addBlankImportRow()">+ Add Row</button><button class="primary" onclick="saveImportedStudents('selected')">Save Selected</button><button class="primary" onclick="saveImportedStudents('all')">Save All Valid</button><button class="secondary" onclick="downloadStudentTemplate()">CSV Template</button></div>`;
 box.querySelectorAll('[data-k]').forEach(inp=>inp.addEventListener('input',updateStudentImportValidation));updateStudentImportValidation();
};
window.addBlankImportRow=function(){syncStudentImportRows();studentImportRows.push(normalizeImportStudent({id:'',name:'',phone:'',aadhaar:'',fatherName:'',motherName:'',course:'',batch:'',joinDate:new Date().toISOString().slice(0,10),monthlyFee:db.settings.monthlyFee||0,status:'Active'}));renderStudentImportPreview();setTimeout(()=>document.querySelector('#studentImportPreview tbody tr:last-child input[data-k="name"]')?.focus(),50)};
window.removeImportRow=function(i){syncStudentImportRows();studentImportRows.splice(i,1);renderStudentImportPreview()};
window.saveImportedStudents=function(mode='all'){
 syncStudentImportRows();let added=0,skipped=[];
 studentImportRows.forEach((r,i)=>{
  const issues=importRowIssues(r,i);if(mode==='selected'&&r._selected===false)return;
  if(issues.length){skipped.push(`${r.name||'Unnamed'}: ${issues.join(', ')}`);return}
  r.id=r.id||nextStudentId();r.phone=String(r.phone||'').replace(/\D/g,'');r.aadhaar=String(r.aadhaar||'').replace(/\D/g,'');r.nextDueDate=addOneMonth(r.joinDate);r.parentName=r.fatherName||r.motherName||'';r.parentPhone=r.fatherPhone||r.motherPhone||'';
  const clean={...r};delete clean._selected;delete clean._issues;db.students.push(clean);added++;
 });
 if(!added)return alert(`No valid students to save. ${skipped.length} rows need correction.`);
 db.importHistory=db.importHistory||[];db.importHistory.push({id:uid(),date:new Date().toISOString(),added,skipped:skipped.length,build:'v2.5 Build 5'});saveDB();closeModal();render('students');alert(`${added} students added successfully. ${skipped.length} rows skipped.`)
};
